Repository dfds/infrastructure-modules, pull requests merged in 2023-09, with the labels that each got.

#1116 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.17
  azure-pipelines.yaml
Labels: norelease

#1115 Avoid printing AWS credentials. Also some formatting of bash script apply_blaster_configmap.sh
  _sub/compute/eks-heptio/apply_blaster_configmap.sh
  _sub/compute/eks-heptio/main.tf
Labels: release:minor

#1117 Remove Atlantis check from this PR template
  .github/pull_request_template.md
Labels: norelease

#1118 chore(deps): update actions/checkout action to v4
  .github/workflows/tflint.yml
Labels: norelease

#1119 Add resource explorer to non-capability/non-legacy
  security/org-account-assume/main.tf
  security/org-account-assume/providers.tf
  security/org-account/main.tf
  security/org-account/vars.tf
Labels: release:minor

#1122 Add resource explorer to legacy-account-context
  security/legacy-account-context/main.tf
Labels: release:minor

#1121 chore(deps): update golang docker tag to v1.21.1
  azure-pipelines.yaml
Labels: norelease

#1125 chore(deps): update terraform github to ~> 5.35.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1126 chore(deps): update terraform github to ~> 5.36.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1127 Create a workflow to create security releases
  .github/workflows/auto-release-security.yml
Labels: norelease

#1128 Remove unused JSON files
  security/org-policies/policies/IntegrityPolicy.json
  security/org-policies/policies/PreventivePolicy.json
  security/org-policies/policies/ReservationPolicy.json
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#1130 Remove unused security sub module
  _sub/security/preprime-iam/README.md
  _sub/security/preprime-iam/main.tf
  _sub/security/preprime-iam/versions.tf
Labels: release:patch

#1129 chore(deps): update terraform datadog to v3.30.0
  _sub/monitoring/datadog-integration-aws/versions.tf
Labels: release:minor

#1133 chore(deps): update module k8s.io/client-go to v0.28.2
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/k8s.io/api/batch/v1/generated.proto
  test/integration/suite/vendor/k8s.io/api/batch/v1/types.go
  test/integration/suite/vendor/k8s.io/client-go/discovery/discovery_client.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1135 chore(deps): update terraform azuread to ~> 2.42.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1141 Fix engine_family local
  _sub/database/postgres/main.tf
Labels: release:patch

#1140 Add db_backup_retention_period variable to enable the tagging policy
  _sub/database/postgres/main.tf
  _sub/database/postgres/vars.tf
  database/postgres/README.md
  database/postgres/main.tf
  database/postgres/vars.tf
Labels: enhancement, release:minor

#1138 Allow passing tags to postgres submodule
  _sub/database/postgres/main.tf
  _sub/database/postgres/vars.tf
  _sub/security/ssm-parameter-store/main.tf
  _sub/security/ssm-parameter-store/vars.tf
  database/postgres/main.tf
  database/postgres/vars.tf
Labels: release:minor

#1144 Update main.tf
  database/postgres/main.tf
Labels: release:patch

#1142 Feature/gpu workloads
  _sub/compute/helm-nvidia-device-plugin/main.tf
  _sub/compute/helm-nvidia-device-plugin/values.yaml
  _sub/compute/helm-nvidia-device-plugin/vars.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
  test/integration/suite/ebs_csi_driver_test.go
  test/integration/suite/fluentd_test.go
  test/integration/suite/kube_proxy_test.go
  test/integration/suite/vpc_cni_driver_test.go
Labels: release:minor

#1146 chore(deps): update terraform azuread to ~> 2.43.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1147 chore(deps): update dependency ami_id to ami-0d028bd9a57562372
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1150 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.18
  azure-pipelines.yaml
Labels: norelease

#1151 Upgrade control plane to 1.28 in QA
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1152 Use AMI for 1.28
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1148 chore(deps): update terraform-linters/setup-tflint action to v4
  .github/workflows/tflint.yml
Labels: norelease

#1137 chore(deps): update terraform github to ~> 5.38.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor
