Repository dfds/infrastructure-modules, pull requests merged in 2023-03, with the labels that each got.

#769 Remove unmanaged node groups
  _sub/compute/eks-nodegroup-unmanaged/dependencies.tf
  _sub/compute/eks-nodegroup-unmanaged/main.tf
  _sub/compute/eks-nodegroup-unmanaged/outputs.tf
  _sub/compute/eks-nodegroup-unmanaged/user-data.sh.tftpl
  _sub/compute/eks-nodegroup-unmanaged/vars.tf
  _sub/compute/eks-nodegroup-unmanaged/versions.tf
  azure-pipelines.yaml
  compute/eks-ec2/main.tf
  compute/eks-ec2/outputs.tf
  compute/eks-ec2/vars.tf
  test/integration/suite/node_test.go
Labels: release:major

#771 Enforce labels on PR
  .github/workflows/enforce-labels.yml
  azure-pipelines.yaml
Labels: release:minor

#775 Update dfdsdk/aws-nuke Docker tag to v0.0.9
  azure-pipelines.yaml
Labels: release:patch

#778 Ability to specify volume types for managed nodes.
  _sub/compute/eks-nodegroup-managed/main.tf
  _sub/compute/eks-nodegroup-managed/vars.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:minor

#780 Ability to use spot instances.
  _sub/compute/eks-nodegroup-managed/main.tf
  _sub/compute/eks-nodegroup-managed/vars.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
Labels: release:minor

#593 removed deny cw logs read access on non eu
  security/org-capability-root/dependencies.tf
Labels: release:minor

#781 Tune atlantis resource requests/limits.
  _sub/compute/helm-atlantis/values/values.yaml
Labels: release:patch

#783 Add support for the new service control policies without destroying the
  _sub/security/org-service-control-policy/main.tf
  _sub/security/org-service-control-policy/vars.tf
  _sub/security/org-service-control-policy/versions.tf
  security/org-capability-root/main.tf
  security/org-policies/dependencies.tf
  security/org-policies/main.tf
  security/org-policies/vars.tf
  security/org-policies/versions.tf
Labels: release:minor

#789 Update Terraform kubernetes to ~> 2.19.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-namespace/version.tf
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-subnet-exporter/version.tf
  compute/eks-ec2/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#790 Use jsondecode and jsonencode to mimimze the JSON payload sent to the AWS Service Control Policy API
  security/org-policies/dependencies.tf
  security/org-policies/main.tf
  security/org-policies/policies/IntegrityPolicy.json
  security/org-policies/policies/PreventivePolicy.json
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch
