Repository dfds/infrastructure-modules, pull requests merged in 2023-12, with the labels that each got.

#1213 chore(deps): update terraform time to v0.9.2
  _sub/compute/helm-crossplane/versions.tf
Labels: release:patch

#1217 chore(deps): update terraform random to ~> 3.6.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/misc/kafka-message/versions.tf
  _sub/security/azure-app-registration/versions.tf
  _sub/security/random-string-generate/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1219 chore(deps): update golang docker tag to v1.21.5
  azure-pipelines.yaml
Labels: norelease

#1222 job config for scraping confluent cloud prometheus metrics added
  _sub/compute/helm-kube-prometheus-stack/main.tf
  _sub/compute/helm-kube-prometheus-stack/values/prometheus.yaml
  _sub/compute/helm-kube-prometheus-stack/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1223 load secrets dynamically for Confluent Metrics scraper
  compute/k8s-services/dependencies.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:patch

#1220 chore(deps): update terraform time to v0.10.0
  _sub/compute/helm-crossplane/versions.tf
Labels: release:minor

#1221 chore(deps): update dependency ami_id to ami-0d739204fa6ce45fd
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1225 Updated expensive ec2 instance types prevention.
  security/org-policies/preventive.tf
Labels: dependencies, norelease

#1227 chore(deps): update module github.com/aws/aws-lambda-go to v1.42.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: norelease

#1228 Upgrade Flux in QA to latest version
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1218 chore(deps): update actions/labeler action to v5
  .github/workflows/labeler.yml
Labels: norelease

#1230 chore(deps): update module github.com/google/uuid to v1.5.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:minor

#1229 Update Atlantis helm chart in QA to 4.18.0
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1231 chore(deps): update terraform flux to ~> 1.2.0
  _sub/compute/k8s-fluxcd/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1236 Add support for tagging policy in compute, database, network and storage
  _sub/network/acm-certificate-san/providers.tf
  _sub/network/acm-certificate-san/vars.tf
  compute/ecr-repo/providers.tf
  compute/ecr-repo/vars.tf
  compute/eks-ec2/providers.tf
  compute/eks-ec2/vars.tf
  compute/k8s-services/providers.tf
  compute/k8s-services/vars.tf
  database/postgres-restore/providers.tf
  database/postgres-restore/vars.tf
  database/postgres/providers.tf
  database/postgres/vars.tf
  network/route53-sub-zone/providers.tf
  network/route53-sub-zone/vars.tf
  storage/s3-ce-cli/providers.tf
  storage/s3-ce-cli/vars.tf
  storage/s3-eks-public/providers.tf
  storage/s3-eks-public/vars.tf
  storage/s3-velero-backup/providers.tf
  storage/s3-velero-backup/vars.tf
  test/integration/account.tfvars
Labels: release:minor

#1232 chore(deps): update github/codeql-action action to v3
  .github/workflows/tfsec.yml
Labels: norelease

#1238 chore(deps): update terraform azuread to ~> 2.47.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1237 chore(deps): update terraform datadog to v3.34.0
  _sub/monitoring/datadog-integration-aws/versions.tf
Labels: release:minor

#1240 Upgrade kube-prometheus-stack in QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/hooks/custom_hook_01.sh
Labels: norelease

#1241 Add support for tagging policy in security modules
  security/cloudtrail-master/providers.tf
  security/cloudtrail-master/vars.tf
  security/iam-identity-center-master/providers.tf
  security/iam-identity-center-master/vars.tf
  security/iam-roles-master/providers.tf
  security/iam-roles-master/vars.tf
  security/iam-roles-qa/providers.tf
  security/iam-roles-qa/vars.tf
  security/iam-users-master/providers.tf
  security/iam-users-master/vars.tf
  security/legacy-account-context/providers.tf
  security/legacy-account-context/vars.tf
  security/org-account-assume/providers.tf
  security/org-account-assume/vars.tf
  security/org-account-context/providers.tf
  security/org-account-context/vars.tf
  security/org-account/providers.tf
  security/org-account/vars.tf
  security/org-capability-root/providers.tf
  security/org-capability-root/vars.tf
  security/org-delegated-administrator-master/providers.tf
  security/org-delegated-administrator-master/vars.tf
  security/org-policies/providers.tf
  security/org-policies/vars.tf
  security/ssh-keypair/providers.tf
  security/ssh-keypair/vars.tf
Labels: release:minor

#1242 Remove support for datadog
  _sub/monitoring/datadog-agent-kubernetes/dependencies.tf
  _sub/monitoring/datadog-agent-kubernetes/main.tf
  _sub/monitoring/datadog-agent-kubernetes/outputs.tf
  _sub/monitoring/datadog-agent-kubernetes/vars.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/datadog-integration-aws/main.tf
  _sub/monitoring/datadog-integration-aws/outputs.tf
  _sub/monitoring/datadog-integration-aws/vars.tf
  _sub/monitoring/datadog-integration-aws/versions.tf
Labels: release:minor

#1244 Removing ckms and old dfds-vault in AWS Backup.
  _sub/security/aws-backup/main.tf
  _sub/security/aws-backup/vars.tf
  security/org-account-context/main.tf
Labels: org-account-context, release:patch

#1245 Enable block on-hold pr
  .github/workflows/block-on-hold-prs.yml
  .github/workflows/housekeeping.yml
Labels: norelease

#1246 Forgot to make the changes to legacy-accounts :-)
  security/legacy-account-context/main.tf
  security/legacy-account-context/vars.tf
  security/org-account-context/vars.tf
Labels: release:patch

#1247 chore(deps): update module github.com/aws/aws-lambda-go to v1.43.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:minor

#1248 chore(deps): update dependency ami_id to ami-05b2a190ca777e72b
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1249 add parameter store item for oidc provider
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:minor
