Repository dfds/infrastructure-modules, pull requests merged in 2023-08, with the labels that each got.

#1069 Allow EKSAdmin role to clean-up flow logs
  security/org-policies/policies/IntegrityPolicy.json
Labels: release:patch

#1071 chore(deps): update golang docker tag to v1.20.7
  azure-pipelines.yaml
Labels: norelease

#1074 Upgrade Flux terraform provider
  _sub/compute/k8s-fluxcd/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1075 Move all providers configs into providers.tf files
  _sub/compute/k8s-fluxcd/main.tf
  _sub/compute/k8s-fluxcd/providers.tf
  _sub/examples/route53-zone/main.tf
  _sub/examples/route53-zone/providers.tf
  _sub/misc/budget-monthly/main.tf
  _sub/misc/budget-monthly/providers.tf
  _sub/misc/budget-monthly/vars.tf
  _sub/network/acm-certificate-san/main.tf
  _sub/network/acm-certificate-san/providers.tf
  compute/ecr-repo/main.tf
  compute/ecr-repo/providers.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/providers.tf
  compute/k8s-services/main.tf
  compute/k8s-services/providers.tf
  database/postgres-restore/main.tf
  database/postgres-restore/providers.tf
  database/postgres/main.tf
  database/postgres/providers.tf
  network/route53-sub-zone/main.tf
  network/route53-sub-zone/providers.tf
  security/cloudtrail-master/main.tf
  security/cloudtrail-master/providers.tf
  security/iam-identity-center-master/main.tf
  security/iam-identity-center-master/providers.tf
  security/iam-roles-master/main.tf
  security/iam-roles-master/providers.tf
  security/iam-roles-qa/main.tf
  security/iam-roles-qa/providers.tf
  security/iam-users-master/main.tf
  security/iam-users-master/providers.tf
  security/legacy-account-context/main.tf
  security/legacy-account-context/providers.tf
  security/org-account-assume/main.tf
  security/org-account-assume/providers.tf
  security/org-account-context/main.tf
  security/org-account-context/providers.tf
  security/org-account/main.tf
  security/org-account/providers.tf
  security/org-capability-root/main.tf
  security/org-capability-root/providers.tf
  security/org-policies/main.tf
  security/org-policies/providers.tf
  security/ssh-keypair/main.tf
  security/ssh-keypair/providers.tf
  storage/s3-ce-cli/main.tf
  storage/s3-ce-cli/providers.tf
  storage/s3-eks-public/main.tf
  storage/s3-eks-public/providers.tf
  storage/s3-velero-backup/main.tf
  storage/s3-velero-backup/providers.tf
Labels: release:patch

#1077 chore(deps): update module github.com/fluxcd/pkg/apis/meta to v1.1.2
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#1076 Disable Kyverno by default and upgrade Helm charts
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1078 Disable serve_from_sub_path by default in Grafana
  _sub/compute/helm-kube-prometheus-stack/main.tf
  _sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
  _sub/compute/helm-kube-prometheus-stack/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1079 Upgrade manifests to use v1 of kustomize.toolkit.fluxcd.io
  _sub/compute/helm-kube-prometheus-stack/dependencies.tf
  _sub/compute/k8s-atlantis-flux-config/dependencies.tf
  _sub/compute/k8s-crossplane-cfg-pkg/dependencies.tf
  _sub/compute/k8s-crossplane-operator/dependencies.tf
  _sub/compute/k8s-crossplane-provider-confluent/dependencies.tf
  _sub/compute/k8s-fluxcd/dependencies.tf
  _sub/compute/k8s-traefik-flux/dependencies.tf
  _sub/examples/podinfo/dependencies.tf
  _sub/monitoring/blackbox-exporter/dependencies.tf
  _sub/monitoring/datadog-agent-kubernetes/dependencies.tf
  _sub/monitoring/fluentd-cloudwatch/dependencies.tf
  _sub/monitoring/helm-exporter/dependencies.tf
  _sub/storage/velero-flux/dependencies.tf
  test/integration/suite/util_flux_test.go
Labels: release:minor

#1083 Add feature toggle for Flux garbage collection. Keeping it on by default
  _sub/compute/helm-kube-prometheus-stack/dependencies.tf
  _sub/compute/helm-kube-prometheus-stack/vars.tf
  _sub/compute/k8s-atlantis-flux-config/dependencies.tf
  _sub/compute/k8s-atlantis-flux-config/vars.tf
  _sub/compute/k8s-crossplane-cfg-pkg/dependencies.tf
  _sub/compute/k8s-crossplane-cfg-pkg/vars.tf
  _sub/compute/k8s-crossplane-operator/dependencies.tf
  _sub/compute/k8s-crossplane-operator/vars.tf
  _sub/compute/k8s-crossplane-provider-confluent/dependencies.tf
  _sub/compute/k8s-crossplane-provider-confluent/vars.tf
  _sub/compute/k8s-fluxcd/dependencies.tf
  _sub/compute/k8s-fluxcd/vars.tf
  _sub/compute/k8s-traefik-flux/dependencies.tf
  _sub/compute/k8s-traefik-flux/vars.tf
  _sub/examples/podinfo/dependencies.tf
  _sub/examples/podinfo/vars.tf
  _sub/monitoring/blackbox-exporter/dependencies.tf
  _sub/monitoring/blackbox-exporter/vars.tf
  _sub/monitoring/datadog-agent-kubernetes/dependencies.tf
  _sub/monitoring/datadog-agent-kubernetes/vars.tf
  _sub/monitoring/fluentd-cloudwatch/dependencies.tf
  _sub/monitoring/fluentd-cloudwatch/vars.tf
  _sub/monitoring/helm-exporter/dependencies.tf
  _sub/monitoring/helm-exporter/vars.tf
  _sub/storage/velero-flux/dependencies.tf
  _sub/storage/velero-flux/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1082 Added norelease label automation and refactored renovate configurations
  .github/pr-labels.yml
  .github/workflows/labeler.yml
  renovate.json
Labels: norelease

#1084 chore(deps): update terraform github to ~> 5.33.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1022 AWS backup for RDS.
  _sub/security/aws-backup/main.tf
  _sub/security/aws-backup/output.tf
  _sub/security/aws-backup/vars.tf
  _sub/security/aws-backup/versions.tf
  security/legacy-account-context/main.tf
  security/legacy-account-context/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: enhancement, release:minor

#1085 Map aws backup reports variables from eks-pipeline into the Atlantis pod
  compute/k8s-services/dependencies.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1087 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.14
  azure-pipelines.yaml
Labels: norelease

#1091 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.15
  azure-pipelines.yaml
Labels: norelease

#1092 chore(deps): update terraform kubernetes to ~> 2.23.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-namespace/version.tf
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-subnet-exporter/version.tf
  _sub/monitoring/aws-node/versions.tf
  compute/eks-ec2/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1094 chore(deps): update dependency ami_id to ami-08b30c137d947bc6e
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1086 Refactoring org-policies to TF objects.
  security/org-policies/integrity.tf
  security/org-policies/main.tf
  security/org-policies/preventive.tf
  security/org-policies/reservation.tf
  security/org-policies/restrictive.tf
  security/org-policies/vars.tf
Labels: enhancement, release:minor

#1096 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.16
  azure-pipelines.yaml
Labels: norelease

#1097 chore(deps): update terraform datadog to v3.29.0
  _sub/monitoring/datadog-integration-aws/versions.tf
Labels: release:minor

#1098 Moving to preventive due to space limit.
  security/org-policies/preventive.tf
  security/org-policies/restrictive.tf
Labels: release:minor

#1099 Fixing terraform object to json issue.
  security/org-policies/main.tf
Labels: bug, release:minor

#1100 chore(deps): update terraform flux to ~> 1.1.0
  _sub/compute/k8s-fluxcd/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1106 chore(deps): update terraform github to ~> 5.34.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1105 chore(deps): update terraform helm to ~> 2.11.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-goldpinger/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-metrics-server/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1107 Fix aws backup vars
  _sub/security/aws-backup/vars.tf
  security/org-account-context/vars.tf
Labels: release:patch

#1108 Update pull_request_template.md
  .github/pull_request_template.md
Labels: norelease

#1109 Rename SID with a capital letter for easy reading.
  security/org-policies/preventive.tf
Labels: release:minor

#1110 Add support for delegated administrator
  _sub/security/org-delegated-administrator/main.tf
  _sub/security/org-delegated-administrator/vars.tf
  _sub/security/org-delegated-administrator/versions.tf
  security/org-delegated-administrator-master/main.tf
  security/org-delegated-administrator-master/providers.tf
  security/org-delegated-administrator-master/vars.tf
  security/org-delegated-administrator-master/versions.tf
Labels: release:minor

#1111 chore(deps): update dependency ami_id to ami-08863056f2ff03fad
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1112 Added housekeeping github action
  .github/workflows/housekeeping.yml
Labels: norelease
