Repository dfds/infrastructure-modules, pull requests merged in 2023-05, with the labels that each got.

#841 use helm exporter 1.2.5 in QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:patch

#842 Update atlantis to 0.33.0 in QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:norelease

#843 Do not create master user key.
  security/iam-users-master/main.tf
  security/iam-users-master/outputs.tf
Labels: release:major

#844 Update azure-pipelines.yaml
  azure-pipelines.yaml
Labels: release:norelease

#846 Update Terraform github to ~> 5.24.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#836 FluentD bumped to latest docker image v1.16
  _sub/monitoring/fluentd-cloudwatch/dependencies.tf
Labels: release:patch

#848 Provider version out of sync with reality
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/security/iam-oidc-provider/versions.tf
  _sub/security/org-account/versions.tf
  compute/eks-ec2/versions.tf
  security/ssh-keypair/versions.tf
  storage/s3-velero-backup/versions.tf
Labels: release:patch

#832 Deny usage of special services
  security/org-policies/main.tf
  security/org-policies/policies/RestrictivePolicy.json
  security/org-policies/vars.tf
Labels: release:major

#851 Update golang Docker tag to v1.20.4
  azure-pipelines.yaml
Labels: release:patch

#849 Updating EKS Add-ons to support EKS 1.26
  _sub/compute/eks-addons/dependencies.tf
Labels: release:minor

#833 Bump from version 44 to 45
  _sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#782 remove adfs from org-account-context
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:major

#852 Restrict grafana dashboard sidecar namespace selector to monitoring
  _sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
Labels: release:patch

#853 Update dependency ami_id to ami-00313eae2f5c20b18
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:minor

#784 remove adfs from org-account-assume
  security/org-account-assume/main.tf
  security/org-account-assume/vars.tf
Labels: release:major

#786 remove adfs resources for org-account
  security/org-account/main.tf
  security/org-account/vars.tf
Labels: release:major

#854 Allow reading your account notifications
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:minor

#856 Updating QA control plane to 1.26
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: eks, release:norelease

#855 Update RestrictivePolicy.json to allow teams to see cost explorer
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:minor

#787 cleanup remaining adfs-related resources
  _sub/security/iam-idp/dependencies.tf
  _sub/security/iam-idp/main.tf
  _sub/security/iam-idp/outputs.tf
  _sub/security/iam-idp/vars.tf
  _sub/security/iam-idp/versions.tf
  _sub/security/iam-policies/main.tf
  _sub/security/iam-policies/outputs.tf
  security/org-account-context/dependencies.tf
  security/org-account-context/main.tf
Labels: release:minor

#857 Update-amiid-to-support-eks-1.26
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: eks, release:norelease

#858 Update RestrictivePolicy.json to allow Access-analyzer outside the eu regions
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:minor

#859 Fix `amiFilter`
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:norelease

#860 Update ami_id digest to amazon-eks-node-1.26-v20230501
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:norelease

#861 Update dependency ami_id to ami-04ffe0600deb5c715
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:norelease

#865 CIS monitoring controls remedies
  _sub/security/cloudtrail-alarm/main.tf
  _sub/security/cloudtrail-alarm/outputs.tf
  _sub/security/cloudtrail-alarm/vars.tf
  _sub/security/cloudtrail-alarm/versions.tf
  _sub/security/cloudtrail-config/main.tf
  _sub/security/cloudtrail-config/outputs.tf
  _sub/security/cloudtrail-config/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:minor

#867 Update CIDR for QA allowed IP addresses in the security group for EKS
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:norelease

#868 CIS monitoring controls remedies
  security/org-account-context/main.tf
Labels: release:minor

#870 SCP Exception for OrgRole to configure AWS Config.
  security/org-policies/policies/IntegrityPolicy.json
Labels: release:patch

#869 Setup a Github Actions TFLint
  .github/workflows/tflint.yml
Labels: enhancement, release:norelease

#866 SCP exception for OrgRole to modify/delete CloudTrail resources.
  security/org-policies/policies/IntegrityPolicy.json
Labels: release:patch

#873 feat: add facility to create sso permission assignments
  _sub/security/iam-identity-center-assignment/main.tf
  _sub/security/iam-identity-center-assignment/outputs.tf
  _sub/security/iam-identity-center-assignment/vars.tf
  _sub/security/iam-identity-center-assignment/versions.tf
  _sub/security/iam-policies/main.tf
  security/org-account-assume/main.tf
  security/org-account-assume/vars.tf
Labels: release:major

#878 Use deploy flag in the AWS config module.
  _sub/security/config-config/main.tf
Labels: release:patch

#877 chore(deps): update terraform azuread to ~> 2.39.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#879 Password policy for hardened accounts.
  security/org-account-context/main.tf
Labels: release:minor

#883 chore(deps): update dfdsdk/prime-pipeline docker tag to v0.6.31
  azure-pipelines.yaml
Labels: release:norelease

#885 Remove ability to create long lived AWS credentials. Also remove unused vars
  _sub/security/iam-user/main.tf
  _sub/security/iam-user/outputs.tf
  _sub/security/iam-user/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:major

#881 Try a different metric filter to resolve CloudWatch.4 control.
  security/org-account-context/main.tf
Labels: release:patch

#886 Enable SSE with customer managed keys for CloudTrail.
  _sub/security/cloudtrail-config/main.tf
  _sub/security/cloudtrail-config/vars.tf
  _sub/storage/s3-cloudtrail-bucket/vars.tf
  security/org-account-context/main.tf
Labels: release:patch

#888 Create a standalone policy before attaching it to a user
  security/iam-users-master/main.tf
Labels: release:patch

#880 Enable server access logging on the CloudTrail bucket in hardened accounts.
  _sub/storage/s3-cloudtrail-bucket/main.tf
  _sub/storage/s3-cloudtrail-bucket/vars.tf
  security/org-account-context/main.tf
Labels: release:minor

#889 Add SupportAccess permission set.
  _sub/security/iam-identity-center/main.tf
Labels: release:minor

#891 Enable AWS config in multiple regions.
  _sub/security/config-config/main.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:minor

#892 Enable CMK key rotation and S3 bucket keys for CloudTrail.
  _sub/security/cloudtrail-config/main.tf
  _sub/storage/s3-cloudtrail-bucket/main.tf
Labels: release:patch

#893 Add support for S3 bucket for kubeconfig being private
  compute/eks-ec2/main.tf
  storage/s3-eks-public/main.tf
  storage/s3-eks-public/vars.tf
Labels: release:minor

#894 Set eks_is_sandbox = true at highest level
  test/integration/account.tfvars
Labels: release:patch

#900 chore(deps): update module k8s.io/client-go to v0.27.2
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/k8s.io/api/batch/v1/generated.proto
  test/integration/suite/vendor/k8s.io/api/batch/v1/types.go
  test/integration/suite/vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  test/integration/suite/vendor/k8s.io/api/core/v1/generated.proto
  test/integration/suite/vendor/k8s.io/api/core/v1/types.go
  test/integration/suite/vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  test/integration/suite/vendor/k8s.io/apimachinery/pkg/types/namespacedname.go
  test/integration/suite/vendor/k8s.io/client-go/discovery/discovery_client.go
  test/integration/suite/vendor/k8s.io/client-go/openapi/client.go
  test/integration/suite/vendor/k8s.io/client-go/openapi/groupversion.go
  test/integration/suite/vendor/modules.txt
Labels: release:norelease

#896 chore(deps): update dependency ami_id to ami-0608033dd04759ae5
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:norelease

#897 chore(deps): update module github.com/stretchr/testify to v1.8.3
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_compare.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_format.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_forward.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_order.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertions.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/doc.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/http_assertions.go
  test/integration/suite/vendor/modules.txt
Labels: release:norelease

#872 Use the flux provider bootstrap resources
  .pre-commit-config.yaml
  _sub/compute/k8s-fluxcd/dependencies.tf
  _sub/compute/k8s-fluxcd/main.tf
  _sub/compute/k8s-fluxcd/migrate-state.sh
  _sub/compute/k8s-fluxcd/vars.tf
  _sub/compute/k8s-fluxcd/versions.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/hooks/custom_hook_01.sh
Labels: release:major

#904 Harden default security groups
  _sub/compute/eks-cluster/network.tf
  security/org-account-context/main.tf
Labels: release:major

#905 Move Deploy user admin permissions from user to group.
  _sub/security/iam-user/main.tf
  _sub/security/iam-user/vars.tf
  security/org-account-context/main.tf
Labels: release:patch

#907 chore(deps): update module github.com/fluxcd/pkg/apis/meta to v1.1.0
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: release:norelease

#906 Enable org-audit CloudWatch log group and KMS CMK key.
  _sub/storage/s3-cloudtrail-bucket/main.tf
  security/cloudtrail-master/main.tf
Labels: release:minor

#908 Only allow non-global services from eu-central-1 and eu-west-1
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:major

#902 feat: add datadog kubernetes operator/agent
  _sub/monitoring/datadog-agent-kubernetes/dependencies.tf
  _sub/monitoring/datadog-agent-kubernetes/main.tf
  _sub/monitoring/datadog-agent-kubernetes/outputs.tf
  _sub/monitoring/datadog-agent-kubernetes/vars.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#909 Determine admin user to manage CMK.
  _sub/security/cloudtrail-config/main.tf
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#912 Patch for case when server access log bucket is not specified.
  _sub/storage/s3-cloudtrail-bucket/data.tf
  _sub/storage/s3-cloudtrail-bucket/main.tf
Labels: release:patch

#913 Add a service for aws-node daemonset in order to scrape its metrics to Prometheus
  _sub/monitoring/aws-node/main.tf
  _sub/monitoring/aws-node/vars.tf
  _sub/monitoring/aws-node/versions.tf
  compute/k8s-services/main.tf
Labels: release:minor

#915 Add support for prime pipeline to Atlantis
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#916 Enable EBS encryption by default in hardened accounts.
  security/org-account-context/main.tf
Labels: release:patch

#917 Feat: enable datadog usm npm
  _sub/monitoring/datadog-agent-kubernetes/dependencies.tf
Labels: release:minor

#920 bugfix/allow larger pvc for atlantis
  _sub/compute/helm-atlantis/main.tf
  _sub/compute/helm-atlantis/values/values.yaml
  _sub/compute/helm-atlantis/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/hooks/custom_hook_01.sh
Labels: release:minor

#918 Fix: add datadog monitoring node tolerating
  _sub/monitoring/datadog-agent-kubernetes/dependencies.tf
  _sub/monitoring/datadog-agent-kubernetes/vars.tf
  compute/k8s-services/main.tf
Labels: release:minor

#921 Increase Atlantis parallelisme
  _sub/compute/helm-atlantis/main.tf
  _sub/compute/helm-atlantis/values/values.yaml
  _sub/compute/helm-atlantis/vars.tf
Labels: release:patch

#922 chore(deps): update dfdsdk/prime-pipeline docker tag to v0.6.32
  azure-pipelines.yaml
Labels: release:norelease

#923 Upgrade Atlantis image to 0.0.38
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:norelease

#924 Add support for Atlantis to pre-prime pipeline
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#925 Add "logs:ListTagsLogGroup", "logs:ListTagsForResource", and "logs:DescribeSubscriptionFilters". Plus formatting
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#927 chore(deps): update module github.com/stretchr/testify to v1.8.4
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: release:norelease

#930 Add support for setting requests.limits.cpu for the Atlantis statefulset. Default null
  _sub/compute/helm-atlantis/main.tf
  _sub/compute/helm-atlantis/values/values.yaml
  _sub/compute/helm-atlantis/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor
