Repository dfds/infrastructure-modules, pull requests merged in 2023-07, with the labels that each got.

#1028 Add missing thumbprint
  _sub/security/iam-github-oidc-provider/main.tf
Labels: release:patch

#1027 chore(deps): update dfdsdk/prime-pipeline docker tag to v0.6.36
  azure-pipelines.yaml
Labels: release:minor

#1030 Fix trust policy for oidc-role
  _sub/security/iam-github-oidc-provider/main.tf
Labels: release:patch

#1031 Fix oidc-role trust policy
  _sub/security/iam-github-oidc-provider/main.tf
  _sub/security/iam-github-oidc-provider/vars.tf
Labels: release:patch

#1033 Fix repositories variable in org-account-context.
  security/org-account-context/vars.tf
Labels: release:patch

#1032 chore(deps): update terraform datadog to v3.27.0
  _sub/monitoring/datadog-integration-aws/versions.tf
Labels: release:norelease

#1034 Fix validation condition
  _sub/security/iam-github-oidc-provider/vars.tf
Labels: release:patch

#1036 chore(deps): update dependency ami_id to ami-027aeda89533df4bb
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:norelease

#1035 feat: add resourceexplorer-read role to org-account-context
  _sub/monitoring/aws-resource-explorer-metrics/main.tf
  _sub/monitoring/aws-resource-explorer-metrics/vars.tf
  _sub/monitoring/aws-resource-explorer-metrics/versions.tf
  security/org-account-context/main.tf
Labels: release:minor

#1038 Turn off optional validation. This field is deprecated and removed in latest major version
  _sub/compute/k8s-fluxcd/dependencies.tf
Labels: release:patch

#1041 Increase Security Bot timeout
  _sub/security/security-bot/main.tf
Labels: release:patch

#1042 Stop hardening the default security groups.
  security/org-account-context/main.tf
Labels: release:patch

#1043 Ability to harden `org-account-assume`-based accounts.
  _sub/security/hardened-account/main.tf
  _sub/security/hardened-account/vars.tf
  _sub/security/hardened-account/versions.tf
  _sub/security/security-bot/main.tf
  _sub/security/security-bot/vars.tf
  security/org-account-assume/main.tf
  security/org-account-assume/vars.tf
  security/org-account-context/main.tf
Labels: release:major

#1047 chore(deps): update terraform github to ~> 5.30.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#1048 chore(deps): update terraform kubernetes to ~> 2.22.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-namespace/version.tf
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-subnet-exporter/version.tf
  _sub/monitoring/aws-node/versions.tf
  compute/eks-ec2/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#1046 chore(deps): update golang docker tag to v1.20.6
  azure-pipelines.yaml
Labels: norelease

#1050 Enable CIS 1.4 in SecurityHub.
  _sub/security/hardened-account/main.tf
Labels: release:patch

#1049 Ability to specify session name in the `org-account-assume` module.
  security/org-account-assume/main.tf
  security/org-account-assume/vars.tf
Labels: release:minor

#1051 Set AWS account name in Security Bot instance.
  _sub/security/hardened-account/main.tf
  _sub/security/security-bot/main.tf
  _sub/security/security-bot/vars.tf
Labels: release:patch

#1061 fix: temporarily revert to legacy grafana alerts
  _sub/compute/helm-kube-prometheus-stack/values/grafana-notifiers.yaml
Labels: release:minor

#1063 fix: re-upgrade to grafana unified alerting
  _sub/compute/helm-kube-prometheus-stack/values/grafana-notifiers.yaml
Labels: release:minor

#1066 Migrate grafana alert configs to modern setup
  _sub/compute/helm-kube-prometheus-stack/dependencies.tf
  _sub/compute/helm-kube-prometheus-stack/main.tf
  _sub/compute/helm-kube-prometheus-stack/values/grafana-notifiers.yaml
  _sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
Labels: release:minor

#1067 chore(deps): update terraform azuread to ~> 2.41.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#1068 Update enforce-labels.yml
  .github/workflows/enforce-labels.yml
Labels: norelease

#1060 chore(deps): update terraform datadog to v3.28.0
  _sub/monitoring/datadog-integration-aws/versions.tf
Labels: release:patch

#1058 chore(deps): update module k8s.io/client-go to v0.27.4
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  test/integration/suite/vendor/k8s.io/apimachinery/pkg/util/wait/loop.go
  test/integration/suite/vendor/k8s.io/client-go/util/cert/cert.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1054 chore(deps): update terraform github to ~> 5.32.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1055 chore(deps): update dependency ami_id to ami-06446fa0d267d38f4
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease
