Repository dfds/infrastructure-modules, pull requests merged in 2023-06, with the labels that each got.

#932 chore(deps): update dependency ami_id to ami-0e2d8a13ac89a0bf0
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:minor

#933 chore(deps): update terraform helm to ~> 2.10.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-goldpinger/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-metrics-server/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#936 Upgrade QA to an EKS 1.27 compatible AMI
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:norelease

#937 enable resource explorer in ou accounts
  security/org-account-context/main.tf
  security/org-account/main.tf
Labels: release:minor

#940 chore(deps): update terraform github to ~> 5.26.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#941 aws_region_2 added for eu-west-1
  security/org-account/main.tf
  security/org-account/vars.tf
Labels: release:patch

#942 Upgrade QA to use kube-prometheus-stack version 46.6.0
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/hooks/custom_hook_01.sh
Labels: release:norelease

#943 chore(deps): update terraform kubernetes to ~> 2.21.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-namespace/version.tf
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-subnet-exporter/version.tf
  _sub/monitoring/aws-node/versions.tf
  compute/eks-ec2/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#944 Reduce unauthorized noise in hardened accounts
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#947 Add DenyResourceExplorer, but allow it for OrgRole and AWS Account Manifests pipeline - in any region
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:minor

#948 Remove datadog from main modules
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  security/org-account-assume/main.tf
  security/org-account-assume/vars.tf
  security/org-account-assume/versions.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
  security/org-account-context/versions.tf
  security/org-account/main.tf
  security/org-account/vars.tf
  security/org-account/versions.tf
Labels: release:major

#949 chore(deps): update golang docker tag to v1.20.5
  azure-pipelines.yaml
Labels: release:norelease

#945 Provide SSO role access in default aws-auth.
  _sub/compute/eks-heptio/default-auth-cm.yaml
  _sub/compute/eks-heptio/dependencies.tf
Labels: release:patch

#950 Modernize and simplify our usage of EKS add-ons
  _sub/compute/eks-addons/dependencies.tf
  _sub/compute/eks-addons/main.tf
  _sub/compute/eks-addons/vars.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
  test/integration/hooks/custom_hook_01.sh
Labels: release:minor

#951 Ability to specify a name/repo for the Fluentd image.
  _sub/monitoring/fluentd-cloudwatch/dependencies.tf
  _sub/monitoring/fluentd-cloudwatch/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#952 Enabe resource explorer in all available regions
  security/org-account-context/main.tf
  security/org-account/main.tf
Labels: release:minor

#953 Disable Fluentd concatenation.
  _sub/monitoring/fluentd-cloudwatch/dependencies.tf
Labels: release:patch

#957 Switch node group variable from list to map.
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:major

#960 chore(deps): update dfdsdk/prime-pipeline docker tag to v0.6.33
  azure-pipelines.yaml
Labels: release:norelease

#958 Exclude S3 storage lens actions from core region only policy.
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#961 chore(deps): update dependency ami_id to ami-05fb5fbb50e08e8be
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:norelease

#956 Limit denying resource explorer policies to actions which create/modify resources.
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#963 Add confluent environment variable to Atlantis pod if crossplane is deployed
  compute/k8s-services/dependencies.tf
  compute/k8s-services/main.tf
Labels: release:minor

#964 fix aws providers auth. remove eu-west-1 resource explorer
  security/org-account/main.tf
Labels: release:minor

#965 Modified datapoints and added slack lambda to log account
  _sub/monitoring/cloudwatch-alarms/log-anomaly/main.tf
  compute/k8s-services/main.tf
Labels: release:patch

#966 Don't disable autoplan on the Atlantis server side
  _sub/compute/helm-atlantis/values/values.yaml
Labels: release:minor

#968 re-enable resource explorer on eu-west-1
  security/org-account/main.tf
Labels: release:patch

#971 chore(deps): update module k8s.io/client-go to v0.27.3
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: release:norelease

#975 Allow the ability to put an alternate contact through the SCP.
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#977 Add module for managing legacy accounts
  _sub/security/org-account/main.tf
  _sub/security/org-account/outputs.tf
  security/legacy-account-context/dependencies.tf
  security/legacy-account-context/main.tf
  security/legacy-account-context/outputs.tf
  security/legacy-account-context/vars.tf
  security/legacy-account-context/versions.tf
Labels: release:minor

#972 remove resource explorer resource in ap and ca regions
  security/org-account-context/main.tf
Labels: release:patch

#979 chore(deps): update terraform github to ~> 5.27.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#980 Allow DeleteAlternateContact
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#982 Exclude account:ListRegions from core region SCP.
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#983 Allow AWS Config recorder access to metadata about KMS key.
  _sub/security/security-bot/main.tf
Labels: release:patch

#976 Set security contact for hardened accounts.
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:patch

#981 more resource resource indexes and providers removed from cap accounts
  security/org-account-context/main.tf
Labels: release:patch

#986 chore(deps): update terraform github to ~> 5.28.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#984 Exclude ssm:DescribeParameters from the core region only policy
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#985 Exclude ec2:DescribeRegions from core region only policy
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#988 Enable the new unified alerting system in Grafana
  _sub/compute/helm-kube-prometheus-stack/values/grafana-notifiers.yaml
Labels: release:minor

#991 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.12
  azure-pipelines.yaml
Labels: release:norelease

#993 Allow the AWS Config recorder to kms:ListResourceTags on Security Bot KMS key.
  _sub/security/security-bot/main.tf
Labels: release:patch

#989 cloudtrail-config kms policy - add support for giving AWS accounts access to key
  _sub/security/cloudtrail-config/main.tf
  _sub/security/cloudtrail-config/vars.tf
  security/cloudtrail-master/main.tf
  security/cloudtrail-master/vars.tf
Labels: release:minor

#994 chore(deps): update dfdsdk/prime-pipeline docker tag to v0.6.34
  azure-pipelines.yaml
Labels: release:norelease

#995 chore(deps): update yogevbd/enforce-label-action action to v2.2.2
  .github/workflows/enforce-labels.yml
Labels: release:norelease

#1000 Fix provider issue
  security/org-account-context/main.tf
Labels: release:patch

#998 chore(deps): update module github.com/fluxcd/pkg/apis/meta to v1.1.1
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: release:norelease

#997 chore(deps): update dfdsdk/prime-pipeline docker tag to v0.6.35
  azure-pipelines.yaml
Labels: release:norelease

#1001 Increase timeout on Security Bot lambda.
  _sub/security/security-bot/main.tf
Labels: release:patch

#1003 Change the Kustomize patch for velero to support the newer Helm chart versions
  _sub/storage/velero-flux/dependencies.tf
Labels: release:major

#1004 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.13
  azure-pipelines.yaml
Labels: release:norelease

#1005 Upgrade kube-prometheus-stack to version 47.0.0 in QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/hooks/custom_hook_01.sh
Labels: release:norelease

#1006 Add support for latest goldpinger.
  _sub/compute/helm-goldpinger/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:major

#1007 Upgrade Atlantis to latest version in QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:norelease

#1009 Exclude descriging reserved offerings from SCPs.
  security/org-policies/policies/ReservationPolicy.json
Labels: release:patch

#1011 Exclude sso:DescribeRegisteredRegions from core region policy.
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#1012 Exclude RDS describe actions from core region only policy.
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#1015 remove resource explorer index in non-eu regions. keep US
  security/legacy-account-context/main.tf
  security/org-account-context/main.tf
Labels: release:patch

#1013 Migrate the billing and cost explorer policies to new IAM actions
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:minor

#1017 Ability to specify AWS session names on account contexts.
  security/legacy-account-context/main.tf
  security/legacy-account-context/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:minor

#1020 chore(deps): update terraform github to ~> 5.29.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1021 unused providers and resources in legacy accounts removed
  security/legacy-account-context/main.tf
Labels: release:patch
