Repository dfds/infrastructure-modules, pull requests merged in 2023-04, with the labels that each got.

#791 Automated inactivity triggered EKS/ELB clean up for sandboxes.
  _sub/compute/eks-alb-auth/outputs.tf
  _sub/compute/eks-alb/outputs.tf
  _sub/compute/eks-cluster/outputs.tf
  _sub/compute/eks-inactivity-cleanup/documents/delete-eks.yaml
  _sub/compute/eks-inactivity-cleanup/main.tf
  _sub/compute/eks-inactivity-cleanup/vars.tf
  _sub/compute/eks-inactivity-cleanup/versions.tf
  _sub/compute/elb-inactivity-cleanup/main.tf
  _sub/compute/elb-inactivity-cleanup/vars.tf
  _sub/compute/elb-inactivity-cleanup/versions.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/outputs.tf
  compute/eks-ec2/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:minor

#793 Update golang Docker tag to v1.20.3
  azure-pipelines.yaml
Labels: release:patch

#794 Update Terraform github to ~> 5.19.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#798 Update dependency ami_id to ami-0454b39c45e1b3450
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:norelease

#799 Update module github.com/fluxcd/pkg/apis/meta to v1
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#797 Update Terraform github to ~> 5.20.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#795 Update dfdsdk/aws-nuke Docker tag to v0.0.10
  azure-pipelines.yaml
Labels: release:norelease

#800 Do not attach the old policies. Keep old policies for unmanaged accounts
  _sub/security/org-policy/main.tf
  _sub/security/org-policy/vars.tf
  security/org-capability-root/main.tf
Labels: release:minor

#803 Change Atlantis resource requests and limits to fix performance and stability issue
  _sub/compute/helm-atlantis/values/values.yaml
Labels: release:patch

#804 Revert "Bumping fluentd container to v1.15 after testing. (#792)"
  _sub/monitoring/fluentd-cloudwatch/dependencies.tf
Labels: release:patch

#809 Turn off CPU limit. Let it rock
  _sub/compute/helm-atlantis/values/values.yaml
Labels: release:patch

#810 Enable postgres storage autoscaling
  _sub/database/postgres-restore/main.tf
  _sub/database/postgres-restore/vars.tf
  _sub/database/postgres/main.tf
  _sub/database/postgres/vars.tf
  database/postgres/README.md
  database/postgres/main.tf
  database/postgres/vars.tf
Labels: release:minor

#813 Update Terraform azuread to ~> 2.37.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#814 postgres.output.connection_string: flag as sensitive
  database/postgres/outputs.tf
Labels: release:patch

#802 Update Terraform github to ~> 5.22.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#815 Update module k8s.io/client-go to v0.27.1
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#816 Remove legacy SCP
  security/org-capability-root/dependencies.tf
  security/org-capability-root/main.tf
Labels: release:minor

#817 Add outputs to the Velero module.
  storage/s3-velero-backup/outputs.tf
Labels: release:minor

#819 monitoring_metrics_server_chart_version = "3.10.0"
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: eks, dependencies, release:patch

#820 Update Terraform github to ~> 5.23.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#818 Allow unsetting with blank string.
  compute/k8s-services/main.tf
Labels: release:minor

#821 Update dependency ami_id to ami-0357203b3e27dd612
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#752 Enable PSS/PSA for some namespaces
  _sub/compute/helm-atlantis/main.tf
  _sub/compute/helm-atlantis/vars.tf
  _sub/compute/helm-crossplane/main.tf
  _sub/compute/helm-crossplane/vars.tf
  _sub/compute/helm-kyverno/main.tf
  _sub/compute/helm-kyverno/vars.tf
  _sub/compute/k8s-blaster-namespace/main.tf
  _sub/compute/k8s-blaster-namespace/vars.tf
  _sub/compute/k8s-fluxcd/main.tf
  _sub/compute/k8s-namespace/main.tf
  _sub/compute/k8s-namespace/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#828 Enable ACLs on buckets before setting ACLs.
  _sub/storage/s3-bucket-lifecycle/main.tf
  _sub/storage/s3-cloudtrail-bucket/main.tf
  storage/s3-velero-backup/main.tf
Labels: release:patch

#825 1522 log alarm
  _sub/monitoring/cloudwatch-alarms/log-anomaly/main.tf
  _sub/monitoring/cloudwatch-alarms/log-anomaly/vars.tf
  _sub/monitoring/cloudwatch-alarms/log-anomaly/versions.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#829 output id from ou in org-capability-root module
  security/org-capability-root/outputs.tf
Labels: release:patch

#827 Allow tagging users
  security/org-policies/policies/RestrictivePolicy.json
Labels: release:patch

#830 Atlantis refactor and prep for staging
  _sub/compute/helm-atlantis/main.tf
  _sub/compute/helm-atlantis/values/values.yaml
  _sub/compute/helm-atlantis/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:major

#834 allow setting of parent_id for org-account
  security/org-account-assume/main.tf
  security/org-account-assume/vars.tf
Labels: release:patch

#835 Refactor all variables with flux_ in the name
  _sub/compute/k8s-atlantis-flux-config/dependencies.tf
  _sub/compute/k8s-atlantis-flux-config/main.tf
  _sub/compute/k8s-atlantis-flux-config/vars.tf
  _sub/compute/k8s-fluxcd/dependencies.tf
  _sub/compute/k8s-fluxcd/vars.tf
  azure-pipelines.yaml
  compute/k8s-services/dependencies.tf
  compute/k8s-services/main.tf
  compute/k8s-services/outputs.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:major

#839 Abillity to specify velero cron schedule.
  _sub/storage/velero-flux/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#840 Retire env variable TF_VAR_platform_fluxcd_github_token
  azure-pipelines.yaml
Labels: release:patch

#838 Update Terraform azuread to ~> 2.38.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  compute/k8s-services/versions.tf
Labels: release:patch

#831 Update Terraform http to ~> 3.3.0
  _sub/security/iam-idp/versions.tf
Labels: release:patch
