Repository dfds/infrastructure-modules, pull requests merged in 2023-10, with the labels that each got.

#1154 Allow AWS Data Exchange service in us-east-1
  security/org-policies/restrictive.tf
Labels: release:minor

#1155 chore(deps): update terraform github to ~> 5.39.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1156 Remove unused variables
  _sub/monitoring/datadog-agent-kubernetes/vars.tf
  compute/eks-ec2/vars.tf
Labels: release:patch

#1157 Supress tfsec warnings on bucket that is by design public
  _sub/storage/s3-bucket/main.tf
Labels: norelease

#1159 RDS is still publicly accessible by default, but this can be changed now
  _sub/database/postgres-restore/main.tf
  _sub/database/postgres-restore/vars.tf
  _sub/database/postgres/main.tf
  _sub/database/postgres/vars.tf
  database/postgres-restore/main.tf
  database/postgres-restore/vars.tf
  database/postgres/main.tf
  database/postgres/vars.tf
Labels: release:patch

#1160 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.19
  azure-pipelines.yaml
Labels: norelease

#1161 chore(deps): update dependency ami_id to ami-078a5e64e57847f0c
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1162 chore(deps): update golang docker tag to v1.21.2
  azure-pipelines.yaml
Labels: norelease

#1164 Enforcing new pod security standards
  compute/k8s-services/vars.tf
Labels: norelease

#1165 feat: add a 24h repeat interval grafana alert notification policy
  _sub/compute/helm-kube-prometheus-stack/dependencies.tf
Labels: release:minor

#1167 Adding a new endpoint for Prometheus.
  _sub/compute/helm-kube-prometheus-stack/values/prometheus.yaml
Labels: release:minor

#1170 Revert "Adding a new endpoint for Prometheus."
  _sub/compute/helm-kube-prometheus-stack/values/prometheus.yaml
Labels: release:patch

#1171 chore(deps): update terraform github to ~> 5.40.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/datadog-agent-kubernetes/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/velero-flux/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1173 Add support for snapshot.storage.k8s.io/v1 API
  _sub/storage/external-snapshotter/dependencies.tf
  _sub/storage/external-snapshotter/main.tf
  _sub/storage/external-snapshotter/vars.tf
  _sub/storage/external-snapshotter/versions.tf
  _sub/storage/velero-flux/dependencies.tf
  compute/k8s-services/main.tf
Labels: release:minor

#1178 Add option to use Velero for creating snapshot backups of EBS volumes
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1174 chore(deps): update terraform datadog to v3.31.0
  _sub/monitoring/datadog-integration-aws/versions.tf
Labels: release:minor

#1181 chore(deps): update terraform azuread to ~> 2.44.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1182 Refactor Velero to get snapshots working in cross-account setups
  _sub/storage/velero-flux/main.tf
  _sub/storage/velero/dependencies.tf
  _sub/storage/velero/main.tf
  _sub/storage/velero/vars.tf
  _sub/storage/velero/versions.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  storage/s3-velero-backup/dependencies.tf
  storage/s3-velero-backup/main.tf
  storage/s3-velero-backup/outputs.tf
  storage/s3-velero-backup/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:major

#1179 Add another backup vault
  _sub/security/aws-backup/main.tf
  _sub/security/aws-backup/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:minor

#1184 Fix legacy-account-context
  security/legacy-account-context/main.tf
Labels: release:patch

#1185 Document how to find compatible AMI images
  README.md
Labels: norelease

#1186 Remove unused variable velero_bucket_name
  compute/k8s-services/vars.tf
Labels: norelease

#1187 chore(deps): update dfdsdk/prime-pipeline docker tag to v0.6.37
  azure-pipelines.yaml
Labels: norelease

#1188 Use latest version of Atlantis image in QA testing
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1191 chore(deps): update terraform azuread to ~> 2.45.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1189 chore(deps): update module github.com/google/uuid to v1.4.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: norelease
