Repository dfds/infrastructure-modules, pull requests merged in 2024-03, with the labels that each got.

#1312 chore(deps): update dependency ami_id to ami-05e357d57b10de349
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1306 feat: add external-secrets module
  _sub/security/external-secrets/dependencies.tf
  _sub/security/external-secrets/main.tf
  _sub/security/external-secrets/vars.tf
  _sub/security/external-secrets/versions.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1314 chore(deps): update module github.com/stretchr/testify to v1.9.0
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_compare.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_format.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_forward.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertions.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/http_assertions.go
  test/integration/suite/vendor/modules.txt
Labels: release:minor

#1316 fix: migrate from inline default route to individual route resource
  _sub/network/route-table/main.tf
Labels: release:patch

#1318 chore(deps): update golang docker tag to v1.22.1
  azure-pipelines.yaml
Labels: release:patch

#1315 Setup IRSA trust between kubernetes cluster and IAM for external-secrets
  _sub/security/external-secrets-ssm/main.tf
  _sub/security/external-secrets-ssm/vars.tf
  _sub/security/external-secrets-ssm/versions.tf
  _sub/security/external-secrets/main.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1319 Add support for Grafana Cloud integration with Cloudwatch for capability, legacy and prime accounts
  _sub/security/grafana-cloud-cloudwatch-integration/main.tf
  _sub/security/grafana-cloud-cloudwatch-integration/outputs.tf
  _sub/security/grafana-cloud-cloudwatch-integration/vars.tf
  _sub/security/grafana-cloud-cloudwatch-integration/versions.tf
  security/legacy-account-context/main.tf
  security/legacy-account-context/outputs.tf
  security/legacy-account-context/vars.tf
  security/org-account-assume/main.tf
  security/org-account-assume/outputs.tf
  security/org-account-assume/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/outputs.tf
  security/org-account-context/vars.tf
Labels: release:minor

#1324 updated ami and renovate settings for QA for upgrading to 1.29
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1325 Update yaml files in k8s-atlantis-flux-config
  _sub/compute/k8s-atlantis-flux-config/dependencies.tf
  _sub/compute/k8s-atlantis-flux-config/main.tf
  _sub/compute/k8s-atlantis-flux-config/values/app-config.yaml
  _sub/compute/k8s-atlantis-flux-config/values/ingressroute.yaml
  _sub/compute/k8s-atlantis-flux-config/values/kustomization.yaml
  _sub/compute/k8s-atlantis-flux-config/values/middleware.yaml
Labels: release:minor

#1328 Update yaml files in blackbox-exporter
  _sub/monitoring/blackbox-exporter/dependencies.tf
  _sub/monitoring/blackbox-exporter/main.tf
  _sub/monitoring/blackbox-exporter/values/app-config.yaml
  _sub/monitoring/blackbox-exporter/values/kustomization.yaml
  _sub/monitoring/blackbox-exporter/values/patch.yaml
  _sub/monitoring/blackbox-exporter/vars.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1329 chore(deps): update terraform github to ~> 6.1.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/monitoring/metrics-server/versions.tf
  _sub/security/external-secrets/versions.tf
  _sub/storage/external-snapshotter/versions.tf
  _sub/storage/velero/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1330 Set VPC Flow log retention to retention_in_days
  _sub/network/vpc-flow-log/vars.tf
  _sub/security/hardened-account/main.tf
Labels: release:minor

#1335 chore(deps): update module k8s.io/client-go to v0.29.3
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/golang/protobuf/ptypes/any.go
  test/integration/suite/vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  test/integration/suite/vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  test/integration/suite/vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  test/integration/suite/vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/impl/message.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/strs/strings.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  test/integration/suite/vendor/google.golang.org/protobuf/internal/version/version.go
  test/integration/suite/vendor/google.golang.org/protobuf/proto/decode.go
  test/integration/suite/vendor/google.golang.org/protobuf/proto/doc.go
  test/integration/suite/vendor/google.golang.org/protobuf/proto/encode.go
  test/integration/suite/vendor/google.golang.org/protobuf/proto/extension.go
  test/integration/suite/vendor/google.golang.org/protobuf/proto/merge.go
  test/integration/suite/vendor/google.golang.org/protobuf/proto/proto.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  test/integration/suite/vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  test/integration/suite/vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  test/integration/suite/vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  test/integration/suite/vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  test/integration/suite/vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#1327 chore(deps): update terraform time to v0.11.1
  _sub/compute/helm-crossplane/versions.tf
Labels: release:minor

#1336 Use correct AWS provider for VPC peering
  _sub/network/vpc-peering-accepter/versions.tf
  _sub/network/vpc-peering-requester/versions.tf
Labels: release:patch

#1331 Refactor external-snapshotter submodule
  _sub/storage/external-snapshotter/dependencies.tf
  _sub/storage/external-snapshotter/main.tf
  _sub/storage/external-snapshotter/values/config-kustomization.yaml
  _sub/storage/external-snapshotter/values/config.yaml
  _sub/storage/external-snapshotter/values/controller-kustomization.yaml
  _sub/storage/external-snapshotter/values/controller.yaml
  _sub/storage/external-snapshotter/values/crd-kustomization.yaml
  _sub/storage/external-snapshotter/values/crd.yaml
Labels: release:minor

#1340 Removed iam:*SAMLProvider deny actions
  security/org-policies/restrictive.tf
Labels: release:patch

#1338 feat: add ssm prerequisites
  _sub/network/vpc-peering-requester/main.tf
Labels: release:minor

#1337 chore(deps): update terraform github to ~> 6.2.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/monitoring/metrics-server/versions.tf
  _sub/security/external-secrets/versions.tf
  _sub/storage/external-snapshotter/versions.tf
  _sub/storage/velero/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1339 chore(deps): update dfdsdk/prime-pipeline docker tag to v0.6.38
  azure-pipelines.yaml
Labels: release:patch

#1343 Added vars for adjusting Grafana agent memory limit and request
  _sub/monitoring/helm-grafana-agent/main.tf
  _sub/monitoring/helm-grafana-agent/values/values.yaml
  _sub/monitoring/helm-grafana-agent/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:patch

#1344 Add support for taints, tolerations and node affinity for the grafana-agent
  _sub/monitoring/helm-grafana-agent/main.tf
  _sub/monitoring/helm-grafana-agent/values/values.yaml
  _sub/monitoring/helm-grafana-agent/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/suite/ebs_csi_driver_test.go
  test/integration/suite/fluentd_test.go
  test/integration/suite/kube_proxy_test.go
  test/integration/suite/vpc_cni_driver_test.go
Labels: release:minor

#1345 Add support for stateful WAL in Grafana Agent
  _sub/monitoring/helm-grafana-agent/main.tf
  _sub/monitoring/helm-grafana-agent/values/values.yaml
  _sub/monitoring/helm-grafana-agent/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/hooks/custom_hook_01.sh
Labels: release:minor
