Repository dfds/infrastructure-modules, pull requests merged in 2024-08, with the labels that each got.

#1491 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.7
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/traefik/traefik/v2/pkg/tls/tls.go
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#1494 Add policies and trust for reading vpc information
  _sub/security/iam-policies/main.tf
  _sub/security/iam-policies/outputs.tf
  security/org-account-context/dependencies.tf
  security/org-account-context/main.tf
Labels: release:minor

#1495 scrape worker nodes logs
  _sub/monitoring/helm-grafana-agent/values/values.yaml
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1497 ensure grafana agent installed correctly in qa
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1498 Update K8S controlplane to 1.30 in QA
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1499 Upgrade K8S nodes til 1.30 in QA
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1500 Use Docker image with opentofu for the pipeline
  azure-pipelines.yaml
Labels: norelease

#1503 chore(deps): update golang docker tag to v1.22.6
  azure-pipelines.yaml
Labels: release:patch

#1506 Upgrade Atlantis. Make usage of OpenTofu more verbose
  azure-pipelines.yaml
  src/qa-test-eks.sh
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1501 chore(deps): update dependency go to v1.22.6
  test/integration/suite/go.mod
Labels: release:patch

#1504 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.8
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/gorilla/mux/.editorconfig
  test/integration/suite/vendor/github.com/gorilla/mux/.gitignore
  test/integration/suite/vendor/github.com/gorilla/mux/AUTHORS
  test/integration/suite/vendor/github.com/gorilla/mux/LICENSE
  test/integration/suite/vendor/github.com/gorilla/mux/Makefile
  test/integration/suite/vendor/github.com/gorilla/mux/README.md
  test/integration/suite/vendor/github.com/gorilla/mux/doc.go
  test/integration/suite/vendor/github.com/gorilla/mux/mux.go
  test/integration/suite/vendor/github.com/gorilla/mux/regexp.go
  test/integration/suite/vendor/github.com/gorilla/mux/route.go
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#1507 Support Atlantis deployments for sandbox repos that are on a personal account instead of an organization account
  _sub/compute/helm-atlantis/main.tf
  _sub/compute/helm-atlantis/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1509 chore(deps): update dependency ami_id to ami-0f1a6febb470709da
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1510 Add IAMRA permission set
  _sub/security/iam-identity-center/dependencies.tf
  _sub/security/iam-identity-center/main.tf
  _sub/security/iam-identity-center/vars.tf
  security/iam-identity-center-master/main.tf
  security/iam-identity-center-master/vars.tf
Labels: release:minor

#1512 Add IAMRA identity center assignment
  security/org-account-assume/main.tf
  security/org-account-assume/vars.tf
Labels: release:minor

#1516 chore(deps): update golang docker tag to v1.23.0
  azure-pipelines.yaml
Labels: release:minor

#1515 chore(deps): update dependency go to v1.23.0
  test/integration/suite/go.mod
Labels: release:minor

#1514 fix(deps): update module sigs.k8s.io/controller-runtime to v0.18.5
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
  test/integration/suite/vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
Labels: norelease

#1518 chore(deps): update terraform kubernetes to ~> 2.32.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/eks-addons/versions.tofu
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-atlantis/versions.tofu
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-crossplane/versions.tofu
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tofu
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-clusterrole/versions.tofu
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tofu
  _sub/compute/k8s-namespace/versions.tf
  _sub/compute/k8s-namespace/versions.tofu
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-priority-class/versions.tofu
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-service-account/versions.tofu
  _sub/compute/k8s-subnet-exporter/versions.tf
  _sub/compute/k8s-subnet-exporter/versions.tofu
  _sub/monitoring/aws-node/versions.tf
  _sub/monitoring/aws-node/versions.tofu
  compute/eks-ec2/versions.tf
  compute/eks-ec2/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1521 fix(deps): update module sigs.k8s.io/controller-runtime to v0.19.0
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  test/integration/suite/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/doc.go
  test/integration/suite/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  test/integration/suite/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/marshal.go
  test/integration/suite/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go
  test/integration/suite/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go
  test/integration/suite/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.prerelease-lifecycle.go
  test/integration/suite/vendor/modules.txt
  test/integration/suite/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  test/integration/suite/vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  test/integration/suite/vendor/sigs.k8s.io/controller-runtime/pkg/client/fieldvalidation.go
  test/integration/suite/vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
Labels: release:minor

#1520 fix(deps): update module github.com/slack-go/slack to v0.14.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
  test/integration/suite/go.mod
Labels: norelease

#1522 chore(deps): update terraform helm to ~> 2.15.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-atlantis/versions.tofu
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-crossplane/versions.tofu
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/monitoring/helm-grafana-agent/versions.tf
  _sub/monitoring/helm-grafana-agent/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1527 chore(deps): update dependency ami_id to ami-006f81214f16a5a27
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease
