Repository dfds/infrastructure-modules, pull requests merged in 2024-02, with the labels that each got.

#1270 chore(deps): update dependency ami_id to ami-007b01e62497deff5
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1283 Bumped GPU node AMI for QA to ami-099cf6455e994ad9d
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1285 chore(deps): update dependency ami_id to ami-0740419db976b5e73
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1287 chore(deps): update golang docker tag to v1.22.0
  azure-pipelines.yaml
Labels: release:patch

#1286 This is to allow accounts to be deleted using root on capability deletion process.
  security/org-policies/restrictive.tf
Labels: dependencies, release:patch, norelease

#1290 chore(deps): update dependency ami_id to ami-0860867c2af7c37ff
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1295 Add support for OIDC trust with GitHub for Terraform/Terragrunt
  _sub/security/iam-github-oidc-provider/main.tf
  _sub/security/iam-github-oidc-provider/vars.tf
  security/org-account/main.tf
  security/org-account/vars.tf
Labels: release:minor

#1296 Add defaults for OIDC
  security/org-account/vars.tf
Labels: release:patch

#1297 Add missing brackets
  security/org-policies/restrictive.tf
Labels: release:patch

#1291 chore(deps): update module k8s.io/api to v0.29.2
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/k8s.io/api/core/v1/generated.proto
  test/integration/suite/vendor/k8s.io/api/core/v1/types.go
  test/integration/suite/vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#1293 chore(deps): update module k8s.io/client-go to v0.29.2
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#1298 Add atlantis var
  compute/k8s-services/dependencies.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1300 chore(deps): update terraform kubernetes to ~> 2.26.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-namespace/version.tf
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-subnet-exporter/version.tf
  _sub/monitoring/aws-node/versions.tf
  compute/eks-ec2/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1301 chore(deps): update module github.com/slack-go/slack to v0.12.4
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:patch

#1302 chore(deps): update terraform github to v6
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/external-snapshotter/versions.tf
  _sub/storage/velero/versions.tf
  compute/k8s-services/versions.tf
Labels: release:major

#1294 chore(deps): update dependency ami_id to ami-05877c180274965b1
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1303 Replace tfsec with trivy
  .github/workflows/tfsec.yml
  .github/workflows/tfsec_pr_commenter.yml
  .github/workflows/trivy.yml
Labels: norelease

#1305 Add GitHub org secret for atlantis
  _sub/compute/helm-atlantis/main.tf
  _sub/compute/helm-atlantis/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1308 Deploy metrics-server with Flux instead of Terraform
  _sub/compute/helm-metrics-server/main.tf
  _sub/compute/helm-metrics-server/outputs.tf
  _sub/compute/helm-metrics-server/values/values.yaml
  _sub/compute/helm-metrics-server/vars.tf
  _sub/monitoring/metrics-server/dependencies.tf
  _sub/monitoring/metrics-server/main.tf
  _sub/monitoring/metrics-server/vars.tf
  _sub/monitoring/metrics-server/versions.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1307 chore(deps): update module github.com/slack-go/slack to v0.12.5
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:patch

#1310 bumped k8s version to 1.29
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:major
