Repository dfds/infrastructure-modules, pull requests merged in 2024-05, with the labels that each got.

#1385 chore(deps): update dependency ami_id to ami-06c25d488ffe0a1e8
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1390 Replace Grafana agent with alloy
  _sub/monitoring/helm-grafana-agent/main.tf
  _sub/monitoring/helm-grafana-agent/values/values.yaml
  _sub/monitoring/helm-grafana-agent/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1392 feat: add steampipe audit role
  _sub/security/steampipe-audit/main.tf
  _sub/security/steampipe-audit/vars.tf
  security/legacy-account-context/main.tf
  security/legacy-account-context/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:major

#1393 Allow changing supportplans if done by OrgRole
  security/org-policies/restrictive.tf
Labels: release:patch

#1391 chore(deps): update golang docker tag to v1.22.3
  azure-pipelines.yaml
Labels: release:patch

#1394 chore(deps): update terraform kubernetes to ~> 2.30.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-namespace/version.tf
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-subnet-exporter/version.tf
  _sub/monitoring/aws-node/versions.tf
  compute/eks-ec2/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1396 chore(deps): update terraform azuread to ~> 2.49.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1398 feat: add steampipe to org-account and org-account-assume
  _sub/security/steampipe-audit/versions.tf
  security/org-account-assume/main.tf
  security/org-account-assume/vars.tf
  security/org-account/main.tf
  security/org-account/vars.tf
Labels: release:major

#1400 fix: set correct aws workload for steampipe-audit org-account-assume
  security/org-account-assume/main.tf
Labels: release:patch

#1402 feat: enable renovate dependency dashboard and schedule
  renovate.json
Labels: norelease

#1401 Add azuread_group submodule
  _sub/security/azuread-group/main.tf
  _sub/security/azuread-group/outputs.tf
  _sub/security/azuread-group/vars.tf
  _sub/security/azuread-group/versions.tf
Labels: release:minor

#1404 Add atlantis vars for grafana cloud app registration
  compute/k8s-services/dependencies.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1405 fix: renovate config update
  renovate.json
Labels: norelease

#1399 chore(deps): update terraform flux to ~> 1.3.0
  _sub/compute/k8s-fluxcd/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1409 Upgrade QA to use Flux 2.3.0
  _sub/compute/k8s-crossplane-operator/dependencies.tf
  _sub/compute/k8s-traefik-flux/dependencies.tf
  _sub/monitoring/blackbox-exporter/values/patch.yaml
  _sub/monitoring/helm-exporter/values/patch.yaml
  _sub/monitoring/metrics-server/dependencies.tf
  _sub/security/external-secrets/dependencies.tf
  _sub/storage/velero/dependencies.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1408 Use ti-platform as cost centre
  test/integration/account.tfvars
Labels: norelease

#1410 Add atlantis vars
  compute/k8s-services/dependencies.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1412 Use YAML instead of JSON for Velero config for Flux
  _sub/storage/velero/dependencies.tf
  _sub/storage/velero/main.tf
  _sub/storage/velero/values/app-config.yaml
  _sub/storage/velero/values/kustomization.yaml
  _sub/storage/velero/values/patch.yaml
  _sub/storage/velero/vars.tf
Labels: release:minor

#1413 Use connection data from Kubernetes data source instead of kubeconfig
  _sub/compute/k8s-fluxcd/providers.tf
  _sub/compute/k8s-fluxcd/vars.tf
  compute/k8s-services/main.tf
Labels: release:minor

#1411 chore(deps): update dependency ami_id to ami-00f34b6d2d1f002b0
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1414 enable passing helm install timeout from hcl file
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:patch

#1415 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.20
  azure-pipelines.yaml
Labels: release:patch

#1417 chore(deps): update dependency publishbuildartifacts to v1.238.1
  azure-pipelines.yaml
Labels: norelease

#1416 fix(deps): update kubernetes packages to v0.30.1
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/k8s.io/api/core/v1/generated.proto
  test/integration/suite/vendor/k8s.io/api/core/v1/types.go
  test/integration/suite/vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  test/integration/suite/vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#1419 chore(deps): update terraform azuread to v2.50.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  _sub/security/azuread-group/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1420 fix(deps): update module github.com/slack-go/slack to v0.13.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:minor

#1407 Move components from prom stack to alloy helm
  _sub/compute/helm-kube-prometheus-stack/main.tf
  _sub/compute/helm-kube-prometheus-stack/values/components.yaml
  _sub/compute/helm-kube-prometheus-stack/values/prometheus.yaml
  _sub/compute/helm-kube-prometheus-stack/vars.tf
  _sub/monitoring/helm-grafana-agent/main.tf
  _sub/monitoring/helm-grafana-agent/outputs.tf
  _sub/monitoring/helm-grafana-agent/values/values.yaml
  _sub/monitoring/helm-grafana-agent/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/hooks/custom_hook_01.sh
Labels: release:minor

#1425 grafana agent chart version in QA updated
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease
