Repository dfds/infrastructure-modules, pull requests merged in 2024-11, with the labels that each got.

#1604 chore(deps): update dependency publishbuildartifacts to v1.247.1
  azure-pipelines.yaml
Labels: release:patch

#1606 Remove crossplane
  .pre-commit-config.yaml
  README.md
  _sub/compute/helm-crossplane/main.tf
  _sub/compute/helm-crossplane/values/values.yaml
  _sub/compute/helm-crossplane/vars.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-crossplane/versions.tofu
  _sub/compute/k8s-crossplane-cfg-pkg/dependencies.tf
  _sub/compute/k8s-crossplane-cfg-pkg/main.tf
  _sub/compute/k8s-crossplane-cfg-pkg/vars.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tofu
  _sub/compute/k8s-crossplane-operator/dependencies.tf
  _sub/compute/k8s-crossplane-operator/main.tf
  _sub/compute/k8s-crossplane-operator/vars.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tofu
  _sub/compute/k8s-crossplane-provider-confluent/dependencies.tf
  _sub/compute/k8s-crossplane-provider-confluent/main.tf
  _sub/compute/k8s-crossplane-provider-confluent/vars.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tofu
  azure-pipelines.yaml
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:major

#1607 Allow EKS pipelines to manage public buckets
  security/org-policies/preventive.tf
Labels: release:patch

#1609 Version lock Velero in QA to avoid runtime errors
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1610 Add support for Apache Druid Operator and fix a few tfsec issues
  _sub/compute/druid-operator/dependencies.tf
  _sub/compute/druid-operator/main.tf
  _sub/compute/druid-operator/values/app-config.yaml
  _sub/compute/druid-operator/values/kustomization.yaml
  _sub/compute/druid-operator/values/patch.yaml
  _sub/compute/druid-operator/vars.tf
  _sub/compute/druid-operator/versions.tf
  _sub/compute/druid-operator/versions.tofu
  _sub/compute/elb-inactivity-cleanup/main.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1599 chore(deps): update dependency ami_id to ami-0a292caa8fe6d443f
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1611 Add Trivy Operator
  _sub/compute/trivy-operator/dependencies.tf
  _sub/compute/trivy-operator/main.tf
  _sub/compute/trivy-operator/values/app-config.yaml
  _sub/compute/trivy-operator/values/kustomization.yaml
  _sub/compute/trivy-operator/values/patch.yaml
  _sub/compute/trivy-operator/vars.tf
  _sub/compute/trivy-operator/versions.tf
  _sub/compute/trivy-operator/versions.tofu
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1608 Prepare Flux for multi-tenancy support
  .pre-commit-config.yaml
  _sub/compute/atlantis/flux.tf
  _sub/compute/atlantis/values/app-config.yaml
  _sub/compute/atlantis/values/patch.yaml
  _sub/compute/druid-operator/main.tf
  _sub/compute/druid-operator/values/app-config.yaml
  _sub/compute/druid-operator/values/patch.yaml
  _sub/compute/github-arc-runners/dependencies.tf
  _sub/compute/github-arc-runners/vars.tf
  _sub/compute/github-arc-ss-controller/dependencies.tf
  _sub/compute/helm-kube-prometheus-stack/dependencies.tf
  _sub/compute/k8s-fluxcd/dependencies.tf
  _sub/compute/k8s-fluxcd/main.tf
  _sub/compute/k8s-fluxcd/values/flux-system-patch.yaml
  _sub/compute/k8s-shared-manifests/values/shared-manifests.yaml
  _sub/compute/k8s-traefik-flux/main.tf
  _sub/compute/k8s-traefik-flux/values/app-config.yaml
  _sub/compute/k8s-traefik-flux/values/app-helm.yaml
  _sub/compute/k8s-traefik-flux/values/helm-patch.yaml
  _sub/compute/nvidia-device-plugin/main.tf
  _sub/compute/nvidia-device-plugin/values/app-config.yaml
  _sub/compute/nvidia-device-plugin/values/patch.yaml
  _sub/compute/trivy-operator/main.tf
  _sub/compute/trivy-operator/values/app-config.yaml
  _sub/compute/trivy-operator/values/patch.yaml
  _sub/monitoring/blackbox-exporter/main.tf
  _sub/monitoring/blackbox-exporter/values/app-config.yaml
  _sub/monitoring/blackbox-exporter/values/patch.yaml
  _sub/monitoring/goldpinger/main.tf
  _sub/monitoring/goldpinger/values/app-config.yaml
  _sub/monitoring/goldpinger/values/patch.yaml
  _sub/monitoring/helm-exporter/main.tf
  _sub/monitoring/helm-exporter/values/app-config.yaml
  _sub/monitoring/helm-exporter/values/patch.yaml
  _sub/monitoring/kafka-exporter/dependencies.tf
  _sub/monitoring/kafka-exporter/main.tf
  _sub/monitoring/kafka-exporter/vars.tf
  _sub/monitoring/metrics-server/dependencies.tf
  _sub/security/external-secrets/dependencies.tf
  _sub/storage/external-snapshotter/values/config.yaml
  _sub/storage/external-snapshotter/values/controller.yaml
  _sub/storage/external-snapshotter/values/crd.yaml
  _sub/storage/velero/main.tf
  _sub/storage/velero/values/app-config.yaml
  _sub/storage/velero/values/patch.yaml
  compute/k8s-services/main.tf
Labels: release:minor

#1613 Add support for Flux multi-tenancy in Grafana
  _sub/monitoring/grafana/main.tf
  _sub/monitoring/grafana/values/app-config.yaml
  _sub/monitoring/grafana/values/patch.yaml
Labels: release:patch

#1614 Added systemReserved to user-data for eks nodegroup
  _sub/compute/eks-nodegroup-managed/user-data.sh.tftpl
Labels: release:minor

#1612 Add flux multitenant setup
  _sub/compute/k8s-fluxcd/main.tf
  _sub/compute/k8s-fluxcd/values/kustomization.yaml
  _sub/compute/k8s-fluxcd/values/rbac.yaml
  _sub/compute/k8s-fluxcd/values/sync.yaml
  _sub/compute/k8s-fluxcd/values/tenants.yaml
  _sub/compute/k8s-fluxcd/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/hooks/custom_hook_01.sh
Labels: release:minor

#1615 Fix tenants input QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1616 Use service account in podifo
  _sub/examples/podinfo/dependencies.tf
Labels: release:minor

#1617 Remove discontinued sub module for shared manifests
  _sub/compute/k8s-shared-manifests/main.tf
  _sub/compute/k8s-shared-manifests/values/shared-manifests.yaml
  _sub/compute/k8s-shared-manifests/vars.tf
  _sub/compute/k8s-shared-manifests/versions.tf
  _sub/compute/k8s-shared-manifests/versions.tofu
  compute/k8s-services/dependencies.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:major

#1618 chore(deps): update dependency ami_id to ami-011639dfca958cf97
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1619 chore(deps): update golang docker tag to v1.23.3
  azure-pipelines.yaml
Labels: norelease

#1621 chore(deps): update dependency ami_id to ami-0c2b9a69bb2076ef4
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1624 Enable versioning of cloudtrail and cloudtrail logging buckets in order to be able to support replication of buckets
  _sub/storage/s3-cloudtrail-bucket/main.tf
Labels: release:minor

#1626 Feature/enable role assignment forazure app registrations
  _sub/security/azure-app-registration/main.tf
  _sub/security/azure-app-registration/outputs.tf
  _sub/security/azure-app-registration/vars.tf
  _sub/security/azure-app-role-assignment/main.tf
  _sub/security/azure-app-role-assignment/vars.tf
  _sub/security/azure-app-role-assignment/versions.tf
  _sub/security/azure-app-role-assignment/versions.tofu
Labels: release:minor

#1629 Add support for ALB bucket replication
  _sub/storage/s3-bucket-lifecycle/main.tf
  _sub/storage/s3-bucket-lifecycle/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1636 chore(deps): update terraform kubectl to ~> 1.16.0
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1635 chore(deps): update terraform github to ~> 6.4.0
  _sub/compute/atlantis/versions.tf
  _sub/compute/atlantis/versions.tofu
  _sub/compute/druid-operator/versions.tf
  _sub/compute/druid-operator/versions.tofu
  _sub/compute/github-arc-runners/versions.tf
  _sub/compute/github-arc-runners/versions.tofu
  _sub/compute/github-arc-ss-controller/versions.tf
  _sub/compute/github-arc-ss-controller/versions.tofu
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tofu
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-fluxcd/versions.tofu
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tofu
  _sub/compute/nvidia-device-plugin/versions.tf
  _sub/compute/nvidia-device-plugin/versions.tofu
  _sub/compute/trivy-operator/versions.tf
  _sub/compute/trivy-operator/versions.tofu
  _sub/examples/podinfo/versions.tf
  _sub/examples/podinfo/versions.tofu
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tofu
  _sub/monitoring/goldpinger/versions.tf
  _sub/monitoring/goldpinger/versions.tofu
  _sub/monitoring/grafana/versions.tf
  _sub/monitoring/grafana/versions.tofu
  _sub/monitoring/helm-exporter/versions.tf
  _sub/monitoring/helm-exporter/versions.tofu
  _sub/monitoring/kafka-exporter/versions.tf
  _sub/monitoring/kafka-exporter/versions.tofu
  _sub/monitoring/metrics-server/versions.tf
  _sub/monitoring/metrics-server/versions.tofu
  _sub/security/atlantis-github-configuration/versions.tf
  _sub/security/atlantis-github-configuration/versions.tofu
  _sub/security/external-secrets/versions.tf
  _sub/security/external-secrets/versions.tofu
  _sub/storage/external-snapshotter/versions.tf
  _sub/storage/external-snapshotter/versions.tofu
  _sub/storage/velero/versions.tf
  _sub/storage/velero/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1637 chore(deps): update terraform kubernetes to ~> 2.34.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/eks-addons/versions.tofu
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tofu
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-clusterrole/versions.tofu
  _sub/compute/k8s-namespace/versions.tf
  _sub/compute/k8s-namespace/versions.tofu
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-priority-class/versions.tofu
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-service-account/versions.tofu
  _sub/compute/k8s-subnet-exporter/versions.tf
  _sub/compute/k8s-subnet-exporter/versions.tofu
  _sub/monitoring/aws-node/versions.tf
  _sub/monitoring/aws-node/versions.tofu
  _sub/security/atlantis-github-configuration/versions.tf
  _sub/security/atlantis-github-configuration/versions.tofu
  compute/eks-ec2/versions.tf
  compute/eks-ec2/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1638 fix(deps): update module github.com/stretchr/testify to v1.10.0
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_compare.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_format.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_forward.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertion_order.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/assertions.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  test/integration/suite/vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1633 fix(deps): update module sigs.k8s.io/controller-runtime to v0.19.2
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease
