Repository dfds/infrastructure-modules, pull requests merged in 2024-12, with the labels that each got.

#1639 api permissions on azuread app
  _sub/security/azure-app-registration/dependencies.tf
  _sub/security/azure-app-registration/main.tf
  _sub/security/azure-app-registration/outputs.tf
  _sub/security/azure-app-registration/vars.tf
  _sub/security/azure-app-role-assignment/main.tf
Labels: release:minor

#1644 feat: add falco
  _sub/security/falco/dependencies.tf
  _sub/security/falco/main.tf
  _sub/security/falco/values/app-config.yaml
  _sub/security/falco/values/kustomization.yaml
  _sub/security/falco/values/patch.yaml
  _sub/security/falco/vars.tf
  _sub/security/falco/versions.tf
  _sub/security/falco/versions.tofu
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1642 fix(deps): update module sigs.k8s.io/controller-runtime to v0.19.3
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#1645 chore(deps): update golang docker tag to v1.23.4
  azure-pipelines.yaml
Labels: norelease

#1646 chore(deps): update terraform kubectl to ~> 1.17.0
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1648 Add support for excluding resource types from Velero backups
  _sub/storage/velero/main.tf
  _sub/storage/velero/values/patch.yaml
  _sub/storage/velero/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1650 groups claim for oauth2 azuread applications
  _sub/security/azure-app-registration/main.tf
  _sub/security/azure-app-registration/vars.tf
Labels: release:minor

#1652 fix(deps): update module github.com/fluxcd/pkg/apis/meta to v1.7.0
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1654 chore(deps): update dependency ami_id to ami-0c038924050982eaa
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1655 fix(deps): update kubernetes packages to v0.31.4
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1657 chore(deps): update terraform kubectl to ~> 1.18.0
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1658 feat: add support for falco custom rules
  _sub/security/falco/main.tf
  _sub/security/falco/values/patch.yaml
  _sub/security/falco/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1659 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.16
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/golang.org/x/sys/unix/ioctl_linux.go
  test/integration/suite/vendor/golang.org/x/sys/unix/mkerrors.sh
  test/integration/suite/vendor/golang.org/x/sys/unix/syscall_linux.go
  test/integration/suite/vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_linux.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_linux.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  test/integration/suite/vendor/golang.org/x/sys/windows/syscall_windows.go
  test/integration/suite/vendor/golang.org/x/sys/windows/types_windows.go
  test/integration/suite/vendor/golang.org/x/sys/windows/zsyscall_windows.go
  test/integration/suite/vendor/golang.org/x/term/README.md
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1661 chore(deps): update terraform kubernetes to ~> 2.35.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/eks-addons/versions.tofu
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tofu
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-clusterrole/versions.tofu
  _sub/compute/k8s-namespace/versions.tf
  _sub/compute/k8s-namespace/versions.tofu
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-priority-class/versions.tofu
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-service-account/versions.tofu
  _sub/compute/k8s-subnet-exporter/versions.tf
  _sub/compute/k8s-subnet-exporter/versions.tofu
  _sub/monitoring/aws-node/versions.tf
  _sub/monitoring/aws-node/versions.tofu
  _sub/security/atlantis-github-configuration/versions.tf
  _sub/security/atlantis-github-configuration/versions.tofu
  compute/eks-ec2/versions.tf
  compute/eks-ec2/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1664 Raise the refreshInterval for Atlantis kubeconfig to 1h
  _sub/compute/atlantis/values/kubeconfigs.yaml
Labels: release:patch

#1665 chore(deps): update dependency ami_id to ami-040eb272f5169e67b
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1666 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.26
  azure-pipelines.yaml
Labels: norelease

#1668 chore(deps): update terraform helm to ~> 2.17.0
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/monitoring/helm-grafana-agent/versions.tf
  _sub/monitoring/helm-grafana-agent/versions.tofu
  _sub/security/atlantis-github-configuration/versions.tf
  _sub/security/atlantis-github-configuration/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch
