Repository dfds/infrastructure-modules, pull requests merged in 2024-09, with the labels that each got.

#1528 feat/alternate contacts
  _sub/security/alternate-contact/main.tf
  _sub/security/alternate-contact/vars.tf
  _sub/security/alternate-contact/versions.tf
  _sub/security/alternate-contact/versions.tofu
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:minor

#1529 Remove fluentd to cloudwatch and also remove log anomely alert
  _sub/monitoring/cloudwatch-alarms/log-anomaly/main.tf
  _sub/monitoring/cloudwatch-alarms/log-anomaly/vars.tf
  _sub/monitoring/cloudwatch-alarms/log-anomaly/versions.tf
  _sub/monitoring/cloudwatch-alarms/log-anomaly/versions.tofu
  _sub/monitoring/fluentd-cloudwatch/dependencies.tf
  _sub/monitoring/fluentd-cloudwatch/main.tf
  _sub/monitoring/fluentd-cloudwatch/vars.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tofu
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1530 chore(deps): update dependency ami_id to ami-0d1a36fce4b1099e5
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1532 Add module and sub module for handling delgating IPAM admin in an organization
  _sub/security/org-delegated-ipam-admin/main.tf
  _sub/security/org-delegated-ipam-admin/vars.tf
  _sub/security/org-delegated-ipam-admin/versions.tf
  _sub/security/org-delegated-ipam-admin/versions.tofu
  security/org-delegated-ipam-admin-master/main.tf
  security/org-delegated-ipam-admin-master/providers.tf
  security/org-delegated-ipam-admin-master/vars.tf
  security/org-delegated-ipam-admin-master/versions.tf
  security/org-delegated-ipam-admin-master/versions.tofu
Labels: release:minor

#1537 Create module for managing AWS IPAM
  _sub/network/ipam-pool/main.tf
  _sub/network/ipam-pool/output.tf
  _sub/network/ipam-pool/vars.tf
  _sub/network/ipam-pool/versions.tf
  _sub/network/ipam-pool/versions.tofu
  _sub/network/ipam-scope/main.tf
  _sub/network/ipam-scope/output.tf
  _sub/network/ipam-scope/vars.tf
  _sub/network/ipam-scope/versions.tf
  _sub/network/ipam-scope/versions.tofu
  _sub/network/ipam/main.tf
  _sub/network/ipam/output.tf
  _sub/network/ipam/vars.tf
  _sub/network/ipam/versions.tf
  _sub/network/ipam/versions.tofu
  network/ipam/main.tf
  network/ipam/providers.tf
  network/ipam/vars.tf
  network/ipam/versions.tf
  network/ipam/versions.tofu
Labels: release:minor

#1538 Add the ability to prefix name and description of IPAM scope and pools
  network/ipam/main.tf
  network/ipam/vars.tf
Labels: release:patch

#1534 chore(deps): update golang docker tag to v1.23.1
  azure-pipelines.yaml
Labels: release:patch

#1535 chore(deps): update dependency publishbuildartifacts to v1.245.1
  azure-pipelines.yaml
Labels: norelease

#1541 fix(deps): update kubernetes packages to v0.31.1
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/k8s.io/api/resource/v1alpha3/generated.pb.go
  test/integration/suite/vendor/k8s.io/api/resource/v1alpha3/generated.proto
  test/integration/suite/vendor/k8s.io/api/resource/v1alpha3/types.go
  test/integration/suite/vendor/k8s.io/api/resource/v1alpha3/types_swagger_doc_generated.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1542 Add support for multiple roles to assume when requesting CIDR range from IPAM
  network/ipam/main.tf
  network/ipam/vars.tf
Labels: release:major

#1543 chore(deps): update dependency ami_id to ami-0eb3c6b810888f6e2
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1548 Feature/update preventive scp
  security/org-policies/preventive.tf
  test/integration/suite/go.mod
Labels: release:patch

#1547 chore(deps): update terraform github to ~> 6.3.0
  _sub/compute/github-arc-runners/versions.tf
  _sub/compute/github-arc-runners/versions.tofu
  _sub/compute/github-arc-ss-controller/versions.tf
  _sub/compute/github-arc-ss-controller/versions.tofu
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-atlantis/versions.tofu
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tofu
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tofu
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tofu
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tofu
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tofu
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-fluxcd/versions.tofu
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tofu
  _sub/compute/nvidia-device-plugin/versions.tf
  _sub/compute/nvidia-device-plugin/versions.tofu
  _sub/examples/podinfo/versions.tf
  _sub/examples/podinfo/versions.tofu
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tofu
  _sub/monitoring/goldpinger/versions.tf
  _sub/monitoring/goldpinger/versions.tofu
  _sub/monitoring/grafana/versions.tf
  _sub/monitoring/grafana/versions.tofu
  _sub/monitoring/helm-exporter/versions.tf
  _sub/monitoring/helm-exporter/versions.tofu
  _sub/monitoring/metrics-server/versions.tf
  _sub/monitoring/metrics-server/versions.tofu
  _sub/security/external-secrets/versions.tf
  _sub/security/external-secrets/versions.tofu
  _sub/storage/external-snapshotter/versions.tf
  _sub/storage/external-snapshotter/versions.tofu
  _sub/storage/velero/versions.tf
  _sub/storage/velero/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1545 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.9
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/go-acme/lego/v4/acme/api/internal/sender/useragent.go
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#1549 Add support for AWS IPAM in VPC Peering modules
  _sub/network/vpc-peering-requester/main.tf
  _sub/network/vpc-peering-requester/outputs.tf
  _sub/network/vpc-peering-requester/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:minor

#1550 Install Apache Druid in shared responsibility model with Data Platform
  _sub/compute/k8s-fluxcd/main.tf
  _sub/compute/k8s-fluxcd/vars.tf
  _sub/compute/k8s-shared-manifests/main.tf
  _sub/compute/k8s-shared-manifests/values/shared-manifests.yaml
  _sub/compute/k8s-shared-manifests/vars.tf
  _sub/compute/k8s-shared-manifests/versions.tf
  _sub/compute/k8s-shared-manifests/versions.tofu
  compute/k8s-services/dependencies.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1554 Update QA SSH public key
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1525 Add support for AL2023
  _sub/compute/eks-nodegroup-managed/dependencies.tf
  _sub/compute/eks-nodegroup-managed/main.tf
  _sub/compute/eks-nodegroup-managed/user-data-al2023.sh.tftpl
  _sub/compute/eks-nodegroup-managed/vars.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:minor

#1552 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.10
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/golang.org/x/mod/LICENSE
  test/integration/suite/vendor/golang.org/x/sys/unix/mkerrors.sh
  test/integration/suite/vendor/golang.org/x/sys/unix/syscall_darwin.go
  test/integration/suite/vendor/golang.org/x/sys/unix/syscall_hurd.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_darwin_amd64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_darwin_arm64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_zos_s390x.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_freebsd_386.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_freebsd_amd64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_freebsd_arm.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_freebsd_riscv64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_linux.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  test/integration/suite/vendor/golang.org/x/sys/windows/syscall_windows.go
  test/integration/suite/vendor/golang.org/x/sys/windows/types_windows.go
  test/integration/suite/vendor/golang.org/x/sys/windows/zsyscall_windows.go
  test/integration/suite/vendor/golang.org/x/term/term_windows.go
  test/integration/suite/vendor/golang.org/x/tools/LICENSE
  test/integration/suite/vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  test/integration/suite/vendor/golang.org/x/tools/go/packages/external.go
  test/integration/suite/vendor/golang.org/x/tools/go/packages/golist.go
  test/integration/suite/vendor/golang.org/x/tools/go/packages/packages.go
  test/integration/suite/vendor/golang.org/x/tools/go/packages/visit.go
  test/integration/suite/vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  test/integration/suite/vendor/golang.org/x/tools/internal/aliases/aliases.go
  test/integration/suite/vendor/golang.org/x/tools/internal/aliases/aliases_go121.go
  test/integration/suite/vendor/golang.org/x/tools/internal/aliases/aliases_go122.go
  test/integration/suite/vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  test/integration/suite/vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  test/integration/suite/vendor/golang.org/x/tools/internal/gcimporter/ureader_yes.go
  test/integration/suite/vendor/golang.org/x/tools/internal/gocommand/invoke.go
  test/integration/suite/vendor/golang.org/x/tools/internal/pkgbits/decoder.go
  test/integration/suite/vendor/golang.org/x/tools/internal/pkgbits/encoder.go
  test/integration/suite/vendor/golang.org/x/tools/internal/pkgbits/frames_go1.go
  test/integration/suite/vendor/golang.org/x/tools/internal/pkgbits/frames_go17.go
  test/integration/suite/vendor/golang.org/x/tools/internal/pkgbits/support.go
  test/integration/suite/vendor/golang.org/x/tools/internal/pkgbits/sync.go
  test/integration/suite/vendor/golang.org/x/tools/internal/pkgbits/syncmarker_string.go
  test/integration/suite/vendor/golang.org/x/tools/internal/pkgbits/version.go
  test/integration/suite/vendor/golang.org/x/tools/internal/stdlib/manifest.go
  test/integration/suite/vendor/golang.org/x/tools/internal/typesinternal/errorcode.go
  test/integration/suite/vendor/golang.org/x/tools/internal/typesinternal/types.go
  test/integration/suite/vendor/golang.org/x/tools/internal/versions/constraint.go
  test/integration/suite/vendor/golang.org/x/tools/internal/versions/constraint_go121.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1555 Fix problem with missing dependencies between Flux manifests in shared-manifests
  _sub/compute/k8s-shared-manifests/values/shared-manifests.yaml
Labels: release:patch

#1556 Update QA
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease
