Repository dfds/infrastructure-modules, pull requests merged in 2024-04, with the labels that each got.

#1349 fix: amended inconsistent conditional in vpc requester optional c sub…
  _sub/network/vpc-peering-requester/main.tf
Labels: release:patch

#1350 chore(deps): update golang docker tag to v1.22.2
  azure-pipelines.yaml
Labels: release:patch

#1348 chore(deps): update dependency ami_id to ami-0e7f06a34d0e91206
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1351 chore(deps): update terraform helm to ~> 2.13.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-goldpinger/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tf
  _sub/monitoring/helm-grafana-agent/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1355 chore(deps): update terraform kubernetes to ~> 2.28.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-namespace/version.tf
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-subnet-exporter/version.tf
  _sub/monitoring/aws-node/versions.tf
  compute/eks-ec2/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1356 feat: allow disabling of vpc endpoints for peering
  _sub/network/vpc-peering-requester/main.tf
  _sub/network/vpc-peering-requester/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:minor

#1358 chore(deps): update dependency ami_id to ami-05ff701182d9fd6b3
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1357 Update Flux manifests for helm-exporter to have human readable YAML
  _sub/monitoring/helm-exporter/dependencies.tf
  _sub/monitoring/helm-exporter/main.tf
  _sub/monitoring/helm-exporter/values/app-config.yaml
  _sub/monitoring/helm-exporter/values/kustomization.yaml
  _sub/monitoring/helm-exporter/values/patch.yaml
  _sub/monitoring/helm-exporter/vars.tf
Labels: release:minor

#1359 chore(deps): update terraform kubernetes to ~> 2.29.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-namespace/version.tf
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-subnet-exporter/version.tf
  _sub/monitoring/aws-node/versions.tf
  compute/eks-ec2/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1362 chore(deps): update terraform azuread to ~> 2.48.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1363 Fixed deprecation
  _sub/compute/helm-kube-prometheus-stack/main.tf
  _sub/security/azure-app-registration/main.tf
Labels: release:minor

#1364 Revert "chore(deps): update terraform helm to ~> 2.13.0"
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-goldpinger/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tf
  _sub/monitoring/helm-grafana-agent/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1365 chore(deps): update dfdsdk/prime-pipeline docker tag to v0.6.39
  azure-pipelines.yaml
Labels: norelease

#1366 Use latest version of Atlantis
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1370 Version lock Grafana
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1369 chore(deps): update module k8s.io/client-go to v0.29.4
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/golang.org/x/net/http2/frame.go
  test/integration/suite/vendor/golang.org/x/net/http2/pipe.go
  test/integration/suite/vendor/golang.org/x/net/http2/server.go
  test/integration/suite/vendor/golang.org/x/net/http2/testsync.go
  test/integration/suite/vendor/golang.org/x/net/http2/transport.go
  test/integration/suite/vendor/golang.org/x/sys/unix/aliases.go
  test/integration/suite/vendor/golang.org/x/sys/unix/mkerrors.sh
  test/integration/suite/vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  test/integration/suite/vendor/golang.org/x/sys/unix/syscall_freebsd.go
  test/integration/suite/vendor/golang.org/x/sys/unix/syscall_linux.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_linux.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_linux.go
  test/integration/suite/vendor/golang.org/x/sys/windows/env_windows.go
  test/integration/suite/vendor/golang.org/x/sys/windows/syscall_windows.go
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#1371 disable kube_state_metrics exporter from grafana agent
  _sub/monitoring/helm-grafana-agent/values/values.yaml
Labels: release:patch

#1372 chore(deps): update dependency ami_id to ami-03f2c27d140f7e9c3
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1377 Update GO
  test/integration/suite/go.mod
Labels: release:patch

#1378 chore(deps): update terraform htpasswd to ~> 1.2.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
Labels: release:minor

#1373 chore(deps): update module github.com/aws/aws-lambda-go to v1.47.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:minor

#1379 Update terraform helm to ~> 2.13.0""
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-goldpinger/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tf
  _sub/monitoring/helm-grafana-agent/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1380 Go is no longer a supported runtime for lambdas. It must now run on Amazon Linux
  _sub/security/security-bot/main.tf
Labels: release:minor

#1381 Feat/increase eks alb timeout
  _sub/compute/eks-alb-auth/main.tf
  _sub/compute/eks-alb/main.tf
Labels: release:minor

#1382 Feature/increase eks alb idletimeout limit raised again
  _sub/compute/eks-alb-auth/main.tf
  _sub/compute/eks-alb/main.tf
Labels: release:minor
