Repository dfds/infrastructure-modules, pull requests merged in 2024-10, with the labels that each got.

#1559 chore(deps): update dependency ami_id to ami-0c0ce812f3f679bd1
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1560 chore(deps): update terraform flux to ~> 1.4.0
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-fluxcd/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:minor

#1562 Allow Public VPCs and Elastic IP
  security/org-policies/preventive.tf
Labels: release:minor

#1564 chore(deps): update golang docker tag to v1.23.2
  azure-pipelines.yaml
Labels: norelease

#1557 Added IMDSv1 Preventive Policies
  security/org-policies/preventive.tf
Labels: release:patch

#1565 chore(deps): update terraform time to v0.12.1
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-crossplane/versions.tofu
Labels: release:patch

#1566 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.11
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1567 Upgrade Control Plane in QA to 1.31
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1568 Upgrade QA nodes to 1.31
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1569 Make usage of azuread provider compliant with version 3 of the provider
  _sub/compute/helm-kube-prometheus-stack/main.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/security/azure-app-registration/main.tf
  _sub/security/azure-app-registration/outputs.tf
  _sub/security/azure-app-registration/versions.tf
  _sub/security/azure-app-registration/versions.tofu
  _sub/security/azuread-group/versions.tf
  _sub/security/azuread-group/versions.tofu
  compute/k8s-services/main.tf
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1563 chore(deps): update terraform azuread to v3.0.2
  _sub/security/azuread-group/versions.tf
  _sub/security/azuread-group/versions.tofu
Labels: release:patch

#1571 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.22
  azure-pipelines.yaml
Labels: norelease

#1572 Remove unnecessary taints and tolerations
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/suite/ebs_csi_driver_test.go
  test/integration/suite/kube_proxy_test.go
  test/integration/suite/node_test.go
  test/integration/suite/vpc_cni_driver_test.go
Labels: norelease

#1573 native ingress enabled for traefik in qa
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1574 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.12
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1575 chore(deps): update dfdsdk/prime-pipeline docker tag to v2.1.0
  azure-pipelines.yaml
Labels: norelease

#1576 chore(deps): update dependency ami_id to ami-0616330afd7cd2ad1
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1577 chore(deps): update dfdsdk/prime-pipeline docker tag to v2.1.1
  azure-pipelines.yaml
Labels: norelease

#1578 fix(deps): update module github.com/slack-go/slack to v0.15.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: norelease

#1579 chore(deps): update terraform kubernetes to ~> 2.33.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/eks-addons/versions.tofu
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-atlantis/versions.tofu
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-crossplane/versions.tofu
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tofu
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-clusterrole/versions.tofu
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tofu
  _sub/compute/k8s-namespace/versions.tf
  _sub/compute/k8s-namespace/versions.tofu
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-priority-class/versions.tofu
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-service-account/versions.tofu
  _sub/compute/k8s-shared-manifests/versions.tf
  _sub/compute/k8s-shared-manifests/versions.tofu
  _sub/compute/k8s-subnet-exporter/versions.tf
  _sub/compute/k8s-subnet-exporter/versions.tofu
  _sub/monitoring/aws-node/versions.tf
  _sub/monitoring/aws-node/versions.tofu
  compute/eks-ec2/versions.tf
  compute/eks-ec2/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1580 chore(deps): update terraform helm to ~> 2.16.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-atlantis/versions.tofu
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-crossplane/versions.tofu
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/monitoring/helm-grafana-agent/versions.tf
  _sub/monitoring/helm-grafana-agent/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1583 All Renovate updates gets treated as patches (requested by rifis) Mass update is happening on Tuesdays for this repo only Patch and Minor updates gets automerged on successful tests
  renovate.json
Labels: norelease

#1585 Do not label major updates. Leave it to the reviewer to asses if it contains breaking changes and then label appropriatly
  renovate.json
Labels: norelease

#1586 Do not run QA pipeline when updating irrelevant static files
  azure-pipelines.yaml
Labels: norelease

#1584 Remove AL2 template
  _sub/compute/eks-nodegroup-managed/dependencies.tf
  _sub/compute/eks-nodegroup-managed/main.tf
  _sub/compute/eks-nodegroup-managed/user-data-al2023.sh.tftpl
  _sub/compute/eks-nodegroup-managed/user-data.sh.tftpl
  _sub/compute/eks-nodegroup-managed/vars.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
Labels: release:major

#1587 Remove unused inputs in QA
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1589 Upgrade Atlantis to 5.7.0 in QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1590 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.25
  azure-pipelines.yaml
Labels: norelease

#1592 chore(deps): update dependency ami_id to ami-04d7644c2706873fe
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1593 Added kafka-exporter module
  _sub/monitoring/kafka-exporter/dependencies.tf
  _sub/monitoring/kafka-exporter/main.tf
  _sub/monitoring/kafka-exporter/vars.tf
  _sub/monitoring/kafka-exporter/versions.tf
  _sub/monitoring/kafka-exporter/versions.tofu
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1597 Changing the Deploy user tag key to be more specific.
  _sub/security/iam-user/main.tf
Labels: org-account-context, norelease

#1596 Create kubeconfig as a secret when atlantis_add_secret_volumes = true
  _sub/compute/atlantis/flux.tf
  _sub/compute/atlantis/values/kubeconfigs.yaml
  _sub/compute/atlantis/values/kustomization.yaml
Labels: release:patch

#1591 efs components added
  _sub/compute/efs-fs/dependencies.tf
  _sub/compute/efs-fs/main.tf
  _sub/compute/efs-fs/outputs.tf
  _sub/compute/efs-fs/vars.tf
  _sub/compute/efs-fs/versions.tf
  _sub/compute/efs-fs/versions.tofu
  _sub/compute/eks-addons/dependencies.tf
  _sub/compute/eks-addons/main.tf
  _sub/compute/eks-addons/vars.tf
  _sub/compute/eks-cluster/network.tf
  _sub/compute/eks-cluster/outputs.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
  test/integration/suite/efs_csi_driver_test.go
Labels: release:minor

#1600 fix(deps): update kubernetes packages to v0.31.2
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: release:patch

#1602 fix(deps): update module sigs.k8s.io/controller-runtime to v0.19.1
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1601 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.13
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/go-acme/lego/v4/acme/api/internal/sender/useragent.go
  test/integration/suite/vendor/github.com/go-acme/lego/v4/challenge/dns01/nameserver.go
  test/integration/suite/vendor/github.com/go-acme/lego/v4/challenge/dns01/precheck.go
  test/integration/suite/vendor/github.com/go-jose/go-jose/v4/CHANGELOG.md
  test/integration/suite/vendor/github.com/go-jose/go-jose/v4/crypter.go
  test/integration/suite/vendor/github.com/go-jose/go-jose/v4/jwk.go
  test/integration/suite/vendor/github.com/go-jose/go-jose/v4/opaque.go
  test/integration/suite/vendor/github.com/go-jose/go-jose/v4/signing.go
  test/integration/suite/vendor/github.com/miekg/dns/README.md
  test/integration/suite/vendor/github.com/miekg/dns/edns.go
  test/integration/suite/vendor/github.com/miekg/dns/scan_rr.go
  test/integration/suite/vendor/github.com/miekg/dns/server.go
  test/integration/suite/vendor/github.com/miekg/dns/svcb.go
  test/integration/suite/vendor/github.com/miekg/dns/types.go
  test/integration/suite/vendor/github.com/miekg/dns/version.go
  test/integration/suite/vendor/github.com/miekg/dns/xfr.go
  test/integration/suite/vendor/github.com/miekg/dns/zduplicate.go
  test/integration/suite/vendor/github.com/miekg/dns/zmsg.go
  test/integration/suite/vendor/github.com/miekg/dns/ztypes.go
  test/integration/suite/vendor/golang.org/x/oauth2/LICENSE
  test/integration/suite/vendor/golang.org/x/oauth2/token.go
  test/integration/suite/vendor/golang.org/x/time/LICENSE
  test/integration/suite/vendor/modules.txt
Labels: release:patch
