Repository dfds/infrastructure-modules, pull requests merged in 2024-01, with the labels that each got.

#1250 chore(deps): update dependency ami_id to ami-0cb55cde69ad81c0b
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1251 chore(deps): update terraform kubernetes to ~> 2.25.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-namespace/version.tf
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-subnet-exporter/version.tf
  _sub/monitoring/aws-node/versions.tf
  compute/eks-ec2/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1252 Remove duplicate tags variable declaration for postgres
  database/postgres/vars.tf
Labels: release:patch

#1253 chore(deps): update terraform github to ~> 5.43.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/external-snapshotter/versions.tf
  _sub/storage/velero/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1255 chore(deps): update module github.com/aws/aws-lambda-go to v1.44.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:minor

#1256 Set tag dfds.env from environment for postgres
  _sub/database/postgres/main.tf
Labels: release:minor

#1257 feat: allow s3 multiregionaccesspoint
  security/org-policies/restrictive.tf
Labels: release:minor

#1261 chore(deps): update dependency ami_id to ami-0cdc583db5fc2be50
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1259 chore(deps): update terraform github to ~> 5.44.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/external-snapshotter/versions.tf
  _sub/storage/velero/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1262 Bumped GPU node AMI for qa to ami-0c18f4378931087e0
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1263 chore(deps): update actions/cache action to v4
  .github/workflows/tflint.yml
Labels: release:major

#1267 Fix block-on-hold-prs github action
  .github/workflows/block-on-hold-prs.yml
Labels: norelease

#1258 chore(deps): update golang docker tag to v1.21.6
  azure-pipelines.yaml
Labels: release:patch

#1268 chore(deps): update module github.com/aws/aws-lambda-go to v1.45.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:minor

#1271 chore(deps): update terraform github to ~> 5.45.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/k8s-atlantis-flux-config/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-crossplane-cfg-pkg/versions.tf
  _sub/compute/k8s-crossplane-operator/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/examples/podinfo/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/fluentd-cloudwatch/versions.tf
  _sub/monitoring/helm-exporter/versions.tf
  _sub/storage/external-snapshotter/versions.tf
  _sub/storage/velero/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1272 chore(deps): update module github.com/google/uuid to v1.6.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:minor

#1273 feat: support custom flux deployments
  _sub/compute/k8s-fluxcd/dependencies.tf
  _sub/compute/k8s-fluxcd/main.tf
  _sub/compute/k8s-fluxcd/vars.tf
  compute/k8s-services/dependencies.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1274 fix: remove unused flux repo and vars accidentally left in
  _sub/compute/k8s-fluxcd/dependencies.tf
  _sub/compute/k8s-fluxcd/vars.tf
  compute/k8s-services/dependencies.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:patch

#1275 Add Grafana Agent
  _sub/monitoring/helm-grafana-agent/main.tf
  _sub/monitoring/helm-grafana-agent/values/values.yaml
  _sub/monitoring/helm-grafana-agent/vars.tf
  _sub/monitoring/helm-grafana-agent/versions.tf
  azure-pipelines.yaml
  compute/k8s-services/dependencies.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1279 Add default null to avoid validation error on plan
  compute/k8s-services/vars.tf
Labels: release:patch

#1278 chore(deps): update module github.com/fluxcd/pkg/apis/meta to v1.3.0
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/golang.org/x/sys/unix/mkerrors.sh
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  test/integration/suite/vendor/golang.org/x/sys/windows/syscall_windows.go
  test/integration/suite/vendor/golang.org/x/sys/windows/zsyscall_windows.go
  test/integration/suite/vendor/modules.txt
Labels: release:minor

#1280 All Grafana Agent vars needs to be optional, becayse Grafana deployment is optional (for now)
  compute/k8s-services/vars.tf
Labels: release:minor

#1281 chore(deps): update module github.com/aws/aws-lambda-go to v1.46.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:minor
