Repository dfds/infrastructure-modules, pull requests merged in 2024-07, with the labels that each got.

#1469 chore(deps): update terraform azuread to v2.53.1
  _sub/security/azuread-group/versions.tf
  _sub/security/azuread-group/versions.tofu
Labels: release:patch

#1471 chore(deps): update golang docker tag to v1.22.5
  azure-pipelines.yaml
Labels: norelease

#1470 chore(deps): update dependency go to v1.22.5
  test/integration/suite/go.mod
Labels: norelease

#1473 feat: optionally mount kubeconfigs secret to atlantis
  _sub/compute/helm-atlantis/main.tf
  _sub/compute/helm-atlantis/values/values.yaml
  _sub/compute/helm-atlantis/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1474 chore(deps): update dependency ami_id to ami-08173a57bd89c4c39
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1476 Remove fluentd from QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/suite/fluentd_test.go
Labels: norelease

#1472 Implement nvidia device plugin flux
  _sub/compute/helm-nvidia-device-plugin/main.tf
  _sub/compute/helm-nvidia-device-plugin/values.yaml
  _sub/compute/helm-nvidia-device-plugin/vars.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tofu
  _sub/compute/nvidia-device-plugin/dependencies.tf
  _sub/compute/nvidia-device-plugin/main.tf
  _sub/compute/nvidia-device-plugin/values/app-config.yaml
  _sub/compute/nvidia-device-plugin/values/kustomization.yaml
  _sub/compute/nvidia-device-plugin/values/patch.yaml
  _sub/compute/nvidia-device-plugin/vars.tf
  _sub/compute/nvidia-device-plugin/versions.tf
  _sub/compute/nvidia-device-plugin/versions.tofu
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: norelease

#1477 Turn off PVC for Grafana to avoid grafana issues in QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1388 fix retention and permissions
  _sub/security/hardened-account/main.tf
  _sub/security/security-bot/main.tf
  _sub/security/security-bot/vars.tf
Labels: release:minor

#1484 fix: re-enable master test
  azure-pipelines.yaml
Labels: norelease

#1482 chore(deps): update terraform time to v0.12.0
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-crossplane/versions.tofu
Labels: release:patch

#1478 fix(deps): update module github.com/slack-go/slack to v0.13.1
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:patch

#1483 vars for grafana cloud pipeline atlantis added
  compute/k8s-services/dependencies.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1486 atlantis docker image updated in qa
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1485 Feat/add dataplatform nodegroup to qa
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/suite/ebs_csi_driver_test.go
  test/integration/suite/kube_proxy_test.go
  test/integration/suite/node_test.go
  test/integration/suite/vpc_cni_driver_test.go
Labels: norelease

#1488 runAsUser updated on atlantis pod
  _sub/compute/helm-atlantis/values/values.yaml
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:patch

#1489 chore(deps): update ami_id digest to amazon-eks-node-1.29-v20240703
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1490 chore(deps): update dfdsdk/prime-pipeline docker tag to v0.6.40
  azure-pipelines.yaml
Labels: release:patch
