Repository dfds/infrastructure-modules, pull requests merged in 2024-06, with the labels that each got.

#1424 chore(deps): update terraform time to v0.11.2
  _sub/compute/helm-crossplane/versions.tf
Labels: release:patch

#1426 Disable Grafana alerting if slack webhook is not set
  _sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1422 Refactor k8s-traefik-flux submodule
  _sub/compute/k8s-traefik-flux/dependencies.tf
  _sub/compute/k8s-traefik-flux/main.tf
  _sub/compute/k8s-traefik-flux/values/app-config.yaml
  _sub/compute/k8s-traefik-flux/values/app-helm.yaml
  _sub/compute/k8s-traefik-flux/values/config-dashboard-ingressroute.yaml
  _sub/compute/k8s-traefik-flux/values/config-init.yaml
  _sub/compute/k8s-traefik-flux/values/helm-install.yaml
  _sub/compute/k8s-traefik-flux/values/helm-patch.yaml
  _sub/compute/k8s-traefik-flux/vars.tf
Labels: release:minor

#1432 re-deploy kube-prom-stats in legacy setup
  _sub/compute/helm-kube-prometheus-stack/values/components.yaml
  _sub/monitoring/helm-grafana-agent/values/values.yaml
Labels: release:patch

#1431 Add blackbox_exporter_namespace variable
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:patch

#1429 chore(deps): update golang docker tag to v1.22.4
  azure-pipelines.yaml
Labels: norelease

#1434 Add certificate and apply_immediately variables to the RDS module
  _sub/database/postgres/main.tf
  _sub/database/postgres/vars.tf
  database/postgres/README.md
  database/postgres/main.tf
  database/postgres/vars.tf
Labels: release:minor

#1427 chore(deps): update dependency ami_id to ami-0ea747dda13fbe2c1
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1428 chore(deps): update dependency go to v1.22.4
  test/integration/suite/go.mod
Labels: norelease

#1436 Run 'go mod vendor' manually to sort out dependency issues
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1437 allow lists for kube-stats and cadvisor metrics updated
  _sub/monitoring/helm-grafana-agent/values/values.yaml
Labels: release:minor

#1438 chore(deps): update terraform azuread to v2.51.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  _sub/security/azuread-group/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1439 custom labels removed in blackbox
  _sub/monitoring/blackbox-exporter/values/patch.yaml
Labels: release:patch

#1440 allow all node exporter metrics
  _sub/monitoring/helm-grafana-agent/values/values.yaml
Labels: release:patch

#1441 Avoid null pointer error in Flux by using empty string as defaut instead of null
  _sub/compute/helm-goldpinger/vars.tf
  _sub/compute/helm-kyverno/vars.tf
  _sub/monitoring/helm-grafana-agent/vars.tf
  _sub/security/external-secrets/vars.tf
  _sub/storage/velero/vars.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:patch

#1443 Upgrade Velero to 4.4.1 in QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1445 atlantis vars updated for grafana stack pipeline
  compute/k8s-services/dependencies.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1446 Deploy Goldpinger with Flux
  _sub/monitoring/goldpinger/dependencies.tf
  _sub/monitoring/goldpinger/main.tf
  _sub/monitoring/goldpinger/values/app-config.yaml
  _sub/monitoring/goldpinger/values/kustomization.yaml
  _sub/monitoring/goldpinger/values/patch.yaml
  _sub/monitoring/goldpinger/vars.tf
  _sub/monitoring/goldpinger/versions.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:major

#1450 chore(deps): update terraform helm to ~> 2.14.0
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-goldpinger/versions.tf
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tf
  _sub/monitoring/helm-grafana-agent/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1451 chore(deps): update terraform kubernetes to ~> 2.31.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/helm-atlantis/versions.tf
  _sub/compute/helm-crossplane/versions.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-nvidia-device-plugin/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-crossplane-provider-confluent/versions.tf
  _sub/compute/k8s-namespace/version.tf
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-subnet-exporter/version.tf
  _sub/monitoring/aws-node/versions.tf
  compute/eks-ec2/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1449 chore(deps): update terraform azuread to v2.52.0
  _sub/compute/helm-kube-prometheus-stack/version.tf
  _sub/security/azure-app-registration/versions.tf
  _sub/security/azuread-group/versions.tf
  compute/k8s-services/versions.tf
Labels: release:minor

#1447 fix(deps): update kubernetes packages to v0.30.2
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1452 Remove the Helm install of Goldpinger. Superseeded by _sub/monitoring/goldpinger
  _sub/compute/helm-goldpinger/main.tf
  _sub/compute/helm-goldpinger/tolerations.yaml
  _sub/compute/helm-goldpinger/vars.tf
  _sub/compute/helm-goldpinger/versions.tf
Labels: release:major

#1453 Turn off public access to the EKS cluster API version endpoint
  _sub/security/eks-version-endpoint/main.tf
  _sub/security/eks-version-endpoint/system-public-info-viewer.yaml
  _sub/security/eks-version-endpoint/vars.tf
  _sub/security/eks-version-endpoint/versions.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
Labels: release:minor

#1454 Migrate grafana agent to flux
  _sub/monitoring/grafana/dependencies.tf
  _sub/monitoring/grafana/main.tf
  _sub/monitoring/grafana/values/app-config.yaml
  _sub/monitoring/grafana/values/kustomization.yaml
  _sub/monitoring/grafana/values/patch.yaml
  _sub/monitoring/grafana/vars.tf
  _sub/monitoring/grafana/versions.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1455 Enable grafana with flux on QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1456 Disable grafana with flux on QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1458 Handle test cases where grafana namespace doesn't exist or lack the statefulset
  test/integration/hooks/custom_hook_01.sh
Labels: norelease

#1457 Enable grafana with helm on QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1460 Legitify POC
  .github/workflows/legitify.yaml
Labels: norelease

#1461 For iam-roles-master, make iam_role_trusted_account_root_arn into a list in order to support multiple ARNs
  _sub/security/iam-policies/main.tf
  security/iam-roles-master/main.tf
  security/iam-roles-master/vars.tf
Labels: release:minor

#1462 chore(deps): update dependency ami_id to ami-03d76896f1d3223f2
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1463 Upgrade velero to 7.0.0 in QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1465 Remove version locking of Velero in QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1466 chore(deps): update terraform azuread to v2.53.0
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/security/azure-app-registration/versions.tf
  _sub/security/azure-app-registration/versions.tofu
  _sub/security/azuread-group/versions.tf
  _sub/security/azuread-group/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:minor
