Repository dfds/infrastructure-modules, pull requests merged in 2025-02, with the labels that each got.

#1706 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.20
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1707 fix(deps): update module github.com/fluxcd/pkg/apis/meta to v1.10.0
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/fluxcd/pkg/apis/meta/conditions.go
  test/integration/suite/vendor/golang.org/x/net/http2/config.go
  test/integration/suite/vendor/golang.org/x/net/http2/config_go124.go
  test/integration/suite/vendor/golang.org/x/net/http2/transport.go
  test/integration/suite/vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  test/integration/suite/vendor/golang.org/x/sys/windows/dll_windows.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1709 Upgrade qa control plane to 1.32
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1711 Upgrade qa nodes to 1.32
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1710 Ensure cluster can be created from scratch without failure to setup EFS addon
  _sub/compute/efs-fs/main.tf
  _sub/compute/efs-fs/vars.tf
  _sub/compute/eks-cluster/eks.tf
  _sub/compute/eks-cluster/securitygroup.tf
  compute/eks-ec2/dependencies.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/providers.tf
Labels: release:minor

#1714 Create the missing credentials in 1password-connect through automation
  _sub/security/helm-1password-connect/main.tf
  _sub/security/helm-1password-connect/vars.tf
  _sub/security/helm-1password-connect/versions.tf
  _sub/security/helm-1password-connect/versions.tofu
  azure-pipelines.yaml
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1718 fix(deps): update module github.com/slack-go/slack to v0.16.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:patch

#1719 velero plugin for aws version bumped
  _sub/storage/velero/vars.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1720 chore(deps): update dependency ami_id to ami-0ce8563ff346ce149
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1722 fix(deps): update module sigs.k8s.io/controller-runtime to v0.20.2
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/evanphx/json-patch/v5/merge.go
  test/integration/suite/vendor/github.com/evanphx/json-patch/v5/patch.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1721 fix(deps): update kubernetes packages to v0.32.2
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1723 chore(deps): update golang docker tag to v1.24.0
  azure-pipelines.yaml
Labels: norelease

#1726 Add support for IRSA fetching of your own secrets
  security/org-account-context/dependencies.tf
Labels: release:minor

#1729 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.21
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/go-acme/lego/v4/acme/api/internal/sender/useragent.go
  test/integration/suite/vendor/github.com/go-acme/lego/v4/acme/api/order.go
  test/integration/suite/vendor/github.com/go-acme/lego/v4/acme/commons.go
  test/integration/suite/vendor/github.com/go-acme/lego/v4/acme/errors.go
  test/integration/suite/vendor/github.com/go-acme/lego/v4/certcrypto/crypto.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1732 Find route tables for VPC peering based on tags or filters
  _sub/network/vpc-peering-accepter/main.tf
  _sub/network/vpc-peering-accepter/vars.tf
Labels: release:minor
