Repository dfds/infrastructure-modules, pull requests merged in 2025-06, with the labels that each got.

#1838 chore(deps): update terraform flux to ~> 1.6.0
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-fluxcd/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1839 fix(deps): update module github.com/aws/aws-lambda-go to v1.49.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:patch

#1841 Enable EKS cluster autoscaling groups to work with KMS enabled on EBS volumes
  _sub/security/hardened-account/main.tf
  _sub/security/kms-key/main.tf
Labels: release:minor

#1842 allow additional permissions on EBS related kms for Terraform can handle resource lifecycle
  _sub/security/kms-key/main.tf
Labels: release:patch

#1843 fix: encode IAM role assume policy and policy for subnet-exporter
  _sub/compute/k8s-subnet-exporter/main.tf
Labels: release:patch

#1846 chore(deps): update golang docker tag to v1.24.4
  azure-pipelines.yaml
Labels: norelease

#1854 Enable velero to restore volumes from shared EBS snapshots encrypted with KMS
  _sub/storage/velero/main.tf
  _sub/storage/velero/values/patch.yaml
  _sub/storage/velero/vars.tf
  azure-pipelines.yaml
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1825 Enable sharing EBS snapshots to other AWS accounts
  _sub/compute/lambda/lambda-from-archive/dependencies.tf
  _sub/compute/lambda/lambda-from-archive/main.tf
  _sub/compute/lambda/lambda-from-archive/outputs.tf
  _sub/compute/lambda/lambda-from-archive/vars.tf
  _sub/compute/lambda/lambda-from-archive/versions.tf
  _sub/compute/lambda/lambda-from-archive/versions.tofu
  _sub/compute/lambda/run-lambda-permission/main.tf
  _sub/compute/lambda/run-lambda-permission/vars.tf
  security/ebs-snapshot-copy/dependencies.tf
  security/ebs-snapshot-copy/main.tf
  security/ebs-snapshot-copy/providers.tf
  security/ebs-snapshot-copy/src/index.js
  security/ebs-snapshot-copy/vars.tf
  security/ebs-snapshot-copy/versions.tf
  security/ebs-snapshot-copy/versions.tofu
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1856 ebs snapshot sharing tf module rename
  security/ebs-snapshot-sharing/dependencies.tf
  security/ebs-snapshot-sharing/main.tf
  security/ebs-snapshot-sharing/providers.tf
  security/ebs-snapshot-sharing/src/index.js
  security/ebs-snapshot-sharing/vars.tf
  security/ebs-snapshot-sharing/versions.tf
  security/ebs-snapshot-sharing/versions.tofu
Labels: release:patch

#1859 fix: update default values for velero_ebs_csi_kms_arn variables. Use empty string instead of null
  compute/k8s-services/vars.tf
Labels: release:patch

#1865 Data lookups as primary way to find route tables for peering
  _sub/compute/eks-cluster/network.tf
  _sub/compute/eks-cluster/vars.tf
  _sub/network/vpc-peering-requester/main.tf
  _sub/network/vpc-peering-requester/vars.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: bug, release:major

#1867 chore(deps): update terraform helm to v3
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/compute/helm-kyverno/main.tf
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/security/atlantis-github-configuration/versions.tf
  _sub/security/atlantis-github-configuration/versions.tofu
  compute/eks-ec2/providers.tf
  compute/k8s-services/providers.tf
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1869 fix(velero): correct casing for volumeSnapshotLocation and add name field
  _sub/storage/velero/values/patch.yaml
Labels: release:patch

#1870 fix(deps): update kubernetes packages to v0.33.2
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1873 fix(terragrunt): disable kube-prometheus-stack deployment in configuration
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease
