Repository dfds/infrastructure-modules, pull requests merged in 2025-08, with the labels that each got.

#1902 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.28 [security]
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1904 chore(deps): update dependency ami_id to ami-015501221c27e945f
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1905 Update renovate.json
  renovate.json
Labels: norelease

#1907 fix: update resource association for_each to use index mapping
  network/ipam/main.tf
  network/ipam/vars.tf
Labels: release:major

#1919 chore(deps): update terraform-linters/setup-tflint action to v5
  .github/workflows/tflint.yml
Labels: norelease

#1912 chore(deps): update dependency aws-efs-csi-driver to v2.1.10-eksbuild.1
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1916 chore(deps): update dependency vpc-cni to v1.20.0-eksbuild.1
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1918 chore(deps): update actions/checkout action to v5
  .github/workflows/tflint.yml
  .github/workflows/vendor-go.yml
Labels: norelease

#1914 chore(deps): update golang docker tag to v1.24.6
  azure-pipelines.yaml
Labels: norelease

#1921 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.27
  azure-pipelines.yaml
Labels: release:patch

#1924 feat(external-secrets): add helm chart version input and update custom hook for ESO installation
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/hooks/custom_hook_01.sh
Labels: norelease

#1927 chore(deps): update dependency kube-proxy to v1.33.3-eksbuild.4
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1928 fix(deps): update kubernetes packages to v0.33.4
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1934 Remove/grafana priorityclass variable
  _sub/monitoring/grafana/main.tf
  _sub/monitoring/grafana/values/patch.yaml
  _sub/monitoring/grafana/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:major

#1935 Add QA pipeline workflow for testing and provisioning
  .github/workflows/qa.yml
Labels: norelease

#1937 Added priorityClassName to kafka-exporter
  _sub/monitoring/kafka-exporter/dependencies.tf
Labels: release:patch

#1938 fix: correct format in OIDC role assumption condition
  _sub/security/iam-github-oidc-provider/main.tf
Labels: release:major

#1939 refactor: remove validation for repository refs in OIDC variables
  _sub/security/iam-github-oidc-provider/vars.tf
  security/oidc-github-workflows/vars.tf
  security/org-account/vars.tf
Labels: release:patch

#1940 fix: correct provider source for archive in versions.tf and versions.tofu
  _sub/compute/lambda/lambda-from-archive/versions.tf
  _sub/compute/lambda/lambda-from-archive/versions.tofu
Labels: release:patch

#1941 Exposed 1password-connect helm chart version as variable to enable locking
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1943 chore(deps): update dependency ami_id to ami-0b4f0090458caff9b
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1944 chore(deps): update dependency aws-ebs-csi-driver to v1.48.0-eksbuild.1
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1950 chore(deps): update actions/download-artifact action to v5
  .github/workflows/qa.yml
Labels: norelease

#1949 chore(deps): update actions/checkout action to v5
  .github/workflows/qa.yml
Labels: norelease
