Repository dfds/infrastructure-modules, pull requests merged in 2025-03, with the labels that each got.

#1733 Use Traefik version 34.4.0
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1731 chore(deps): update terraform flux to ~> 1.5.0
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-fluxcd/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1736 chore(deps): update dependency ami_id to ami-03378472383870f22
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1741 chore(deps): update terraform kubernetes to ~> 2.36.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/eks-addons/versions.tofu
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tofu
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-clusterrole/versions.tofu
  _sub/compute/k8s-namespace/versions.tf
  _sub/compute/k8s-namespace/versions.tofu
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-priority-class/versions.tofu
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-service-account/versions.tofu
  _sub/compute/k8s-subnet-exporter/versions.tf
  _sub/compute/k8s-subnet-exporter/versions.tofu
  _sub/monitoring/aws-node/versions.tf
  _sub/monitoring/aws-node/versions.tofu
  _sub/security/atlantis-github-configuration/versions.tf
  _sub/security/atlantis-github-configuration/versions.tofu
  compute/eks-ec2/versions.tf
  compute/eks-ec2/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1742 chore(deps): update terraform random to ~> 3.7.0
  _sub/compute/atlantis/versions.tf
  _sub/compute/atlantis/versions.tofu
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tofu
  _sub/misc/kafka-message/versions.tf
  _sub/misc/kafka-message/versions.tofu
  _sub/security/atlantis-github-configuration/versions.tf
  _sub/security/atlantis-github-configuration/versions.tofu
  _sub/security/azure-app-registration/versions.tf
  _sub/security/azure-app-registration/versions.tofu
  _sub/security/random-string-generate/versions.tf
  _sub/security/random-string-generate/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1738 Fixed bug where no autoscaling is scheduled for sandboxes after refactoring
  _sub/compute/eks-nodegroup-managed/dependencies.tf
  _sub/compute/eks-nodegroup-managed/main.tf
  _sub/compute/eks-nodegroup-managed/vars.tf
Labels: release:minor

#1737 Add support for optional login to Docker Hub
  _sub/compute/eks-nodegroup-managed/main.tf
  _sub/compute/eks-nodegroup-managed/user-data.sh.tftpl
  _sub/compute/eks-nodegroup-managed/vars.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
Labels: release:minor

#1744 Add a new variable to control the port number that blackbox exporter should contact the Traefik endpoint on
  compute/k8s-services/dependencies.tf
  compute/k8s-services/vars.tf
Labels: release:patch

#1745 chore(deps): update golang docker tag to v1.24.1
  azure-pipelines.yaml
Labels: norelease

#1746 fix(deps): update module github.com/traefik/traefik/v2 to v3
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  test/integration/suite/vendor/github.com/emicklei/go-restful/v3/README.md
  test/integration/suite/vendor/github.com/emicklei/go-restful/v3/compress.go
  test/integration/suite/vendor/github.com/emicklei/go-restful/v3/entity_accessors.go
  test/integration/suite/vendor/github.com/emicklei/go-restful/v3/json.go
  test/integration/suite/vendor/github.com/emicklei/go-restful/v3/jsoniter.go
  test/integration/suite/vendor/github.com/emicklei/go-restful/v3/jsr311.go
  test/integration/suite/vendor/github.com/go-openapi/jsonreference/.golangci.yml
  test/integration/suite/vendor/github.com/go-openapi/jsonreference/README.md
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1747 Add variables for Docker Hub credentials
  azure-pipelines.yaml
Labels: norelease

#1743 Feature/velero-enable-fsb-efs-backup
  _sub/storage/velero/main.tf
  _sub/storage/velero/values/patch.yaml
  _sub/storage/velero/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1749 Add enable_scale_to_zero_after_business_hours and use for scaling sandboxes down after business hours
  _sub/compute/eks-nodegroup-managed/dependencies.tf
  _sub/compute/eks-nodegroup-managed/main.tf
  _sub/compute/eks-nodegroup-managed/vars.tf
  compute/eks-ec2/dependencies.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1750 fix(deps): update module sigs.k8s.io/controller-runtime to v0.20.3
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1755 Traefik ingressroute for dashboard is now handled by the helm chart
  _sub/compute/k8s-traefik-flux/dependencies.tf
  _sub/compute/k8s-traefik-flux/main.tf
  _sub/compute/k8s-traefik-flux/values/app-config.yaml
  _sub/compute/k8s-traefik-flux/values/config-dashboard-ingressroute.yaml
  _sub/compute/k8s-traefik-flux/values/config-init.yaml
  _sub/compute/k8s-traefik-flux/values/helm-patch.yaml
Labels: release:major

#1756 chore(deps): update dependency ami_id to ami-07f6e1dfbf631e447
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1760 Add missing parentheses around PathPrefix rules for the Traefik Dashboard ingressroute
  _sub/compute/k8s-traefik-flux/values/helm-patch.yaml
Labels: release:patch

#1757 fix(deps): update kubernetes packages to v0.32.3
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/k8s.io/api/resource/v1alpha3/types.go
  test/integration/suite/vendor/k8s.io/api/resource/v1beta1/types.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1754 Enabe trustedadvisor in capability account
  security/org-policies/restrictive.tf
Labels: release:minor

#1748 disable efs automated backup by default
  compute/eks-ec2/vars.tf
Labels: release:minor

#1761 Change subnets for traefik_alb_anon only when enabling NAT gateway
  compute/k8s-services/main.tf
Labels: release:minor

#1762 chore(deps): update dependency ami_id to ami-07afb5fd28d8564d1
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1764 chore(deps): update terraform azuread to v3.2.0
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/security/azure-app-delegated-permissions-grant/versions.tf
  _sub/security/azure-app-delegated-permissions-grant/versions.tofu
  _sub/security/azure-app-registration/versions.tf
  _sub/security/azure-app-registration/versions.tofu
  _sub/security/azure-app-role-assignment/versions.tf
  _sub/security/azure-app-role-assignment/versions.tofu
  _sub/security/azuread-group/versions.tf
  _sub/security/azuread-group/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1768 fix(deps): update module sigs.k8s.io/controller-runtime to v0.20.4
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
  test/integration/suite/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/restmapper.go
Labels: norelease

#1769 Add a feature toggle to determine if VPC Peering connections should automatically be migrated to new route tables. Default false
  _sub/network/route-table/main.tf
  _sub/network/route-table/vars.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
Labels: release:major
