Repository dfds/infrastructure-modules, pull requests merged in 2025-10, with the labels that each got.

#2024 fix: sort github repositories for atlantis configuration
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:patch

#2028 refactor: update kustomization patches to use new format for HelmRelease targets
  _sub/compute/druid-operator/values/kustomization.yaml
  _sub/compute/github-arc-runners/dependencies.tf
  _sub/compute/github-arc-ss-controller/dependencies.tf
  _sub/compute/k8s-traefik-flux/main.tf
  _sub/compute/k8s-traefik-flux/values/helm-install.yaml
  _sub/compute/keda/values/kustomization.yaml
  _sub/compute/nvidia-device-plugin/values/kustomization.yaml
  _sub/compute/trivy-operator/values/kustomization.yaml
  _sub/monitoring/blackbox-exporter/values/kustomization.yaml
  _sub/monitoring/goldpinger/main.tf
  _sub/monitoring/goldpinger/values/kustomization.yaml
  _sub/monitoring/grafana/values/kustomization.yaml
  _sub/monitoring/metrics-server/dependencies.tf
  _sub/network/external-dns/values/helm-install.yaml
  _sub/security/external-secrets/dependencies.tf
  _sub/security/falco/values/kustomization.yaml
  _sub/storage/velero/values/kustomization.yaml
Labels: release:patch

#2030 Limit patching as much as possible for druid-operator
  _sub/compute/druid-operator/dependencies.tf
  _sub/compute/druid-operator/main.tf
  _sub/compute/druid-operator/values/app-config.yaml
  _sub/compute/druid-operator/values/kustomization.yaml
  _sub/compute/druid-operator/values/patch.yaml
  _sub/compute/druid-operator/vars.tf
  _sub/compute/keda/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:major

#2039 Revert "Change access config to API_AND_CONFIG_MAP to allow API access entries"
  _sub/compute/eks-cluster/eks.tf
Labels: norelease

#2040 refactor: standardize deployment name usage and remove redundant variables in 1Password Connect configuration. Also use post build substitution
  _sub/security/helm-1password-connect/dependencies.tf
  _sub/security/helm-1password-connect/iam.tf
  _sub/security/helm-1password-connect/main.tf
  _sub/security/helm-1password-connect/vars.tf
  compute/k8s-services/main.tf
Labels: release:minor
