Repository dfds/infrastructure-modules, pull requests merged in 2025-09, with the labels that each got.

#1961 chore(deps): update dependency vpc-cni to v1.20.1-eksbuild.3
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1962 chore(deps): update dfdsdk/aws-nuke docker tag to v0.0.30
  .github/workflows/nuke-qa.yml
Labels: norelease

#1960 chore(deps): update dependency kube-proxy to v1.33.3-eksbuild.6
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1967 enable adding custom owners on azure AD besides from default owner
  _sub/security/azure-app-registration/dependencies.tf
  _sub/security/azure-app-registration/main.tf
  _sub/security/azure-app-registration/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1970 chore(deps): update dependency aws-efs-csi-driver to v2.1.11-eksbuild.1
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1976 chore(deps): update aws-actions/configure-aws-credentials action to v5
  .github/workflows/nuke-qa.yml
  .github/workflows/qa.yml
Labels: norelease

#1975 chore(deps): update actions/setup-go action to v6
  .github/workflows/qa.yml
  .github/workflows/vendor-go.yml
Labels: norelease

#1981 chore(deps): update dependency ami_id to ami-0bb2a340502ca7027
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1986 feat(security): add condition to deny actions for specific IAM role
  security/org-policies/preventive.tf
Labels: release:patch

#1993 chore(deps): update terraform htpasswd to ~> 1.4.0
  _sub/compute/atlantis/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tf
Labels: release:patch

#1999 Fix mixup of username and password for dockerhub again
  .github/workflows/qa.yml
Labels: norelease

#1996 Update security bot main.tf to update lambda runtime
  _sub/security/security-bot/main.tf
Labels: release:minor

#2009 Feature/support-multiple-vpc-peers
  _sub/network/vpc-peering-accepter/main.tf
  _sub/network/vpc-peering-accepter/vars.tf
  _sub/network/vpc-peering-requester/main.tf
  _sub/network/vpc-peering-requester/outputs.tf
  _sub/network/vpc-peering-requester/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/providers.tf
  security/org-account-context/vars.tf
Labels: release:major

#2014 feat: refactor OIDC provider configuration for multiple clusters and add standby IAM role
  _sub/security/ssm-parameter-store/main.tf
  _sub/security/ssm-parameter-store/vars.tf
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
  security/org-account-context/dependencies.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:major

#2016 chore(deps): update dependency ami_id to ami-046a1ca9cb9520db5
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#2018 chore(deps): update dependency vpc-cni to v1.20.3-eksbuild.1
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#2019 fix(deps): update module github.com/traefik/traefik/v3 to v3.5.3
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/traefik/traefik/v3/pkg/config/dynamic/http_config.go
  test/integration/suite/vendor/github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/traefikio/v1alpha1/serverstransport.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#2015 refactor external-dns logic to access route53 resources
  compute/k8s-services/dependencies.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:patch
