Repository dfds/infrastructure-modules, pull requests merged in 2025-04, with the labels that each got.

#1771 fix(deps): update module github.com/traefik/traefik/v3 to v3.3.5
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  test/integration/suite/vendor/github.com/go-jose/go-jose/v4/README.md
  test/integration/suite/vendor/github.com/go-jose/go-jose/v4/jwe.go
  test/integration/suite/vendor/github.com/go-jose/go-jose/v4/jwk.go
  test/integration/suite/vendor/github.com/go-jose/go-jose/v4/jws.go
  test/integration/suite/vendor/golang.org/x/net/http2/http2.go
  test/integration/suite/vendor/golang.org/x/net/http2/server.go
  test/integration/suite/vendor/golang.org/x/net/http2/transport.go
  test/integration/suite/vendor/golang.org/x/net/http2/write.go
  test/integration/suite/vendor/golang.org/x/net/internal/httpcommon/ascii.go
  test/integration/suite/vendor/golang.org/x/net/internal/httpcommon/headermap.go
  test/integration/suite/vendor/golang.org/x/net/internal/httpcommon/request.go
  test/integration/suite/vendor/golang.org/x/sync/errgroup/errgroup.go
  test/integration/suite/vendor/golang.org/x/sync/errgroup/go120.go
  test/integration/suite/vendor/golang.org/x/sync/errgroup/pre_go120.go
  test/integration/suite/vendor/golang.org/x/sys/unix/auxv.go
  test/integration/suite/vendor/golang.org/x/sys/unix/auxv_unsupported.go
  test/integration/suite/vendor/golang.org/x/sys/unix/syscall_solaris.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  test/integration/suite/vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  test/integration/suite/vendor/golang.org/x/sys/unix/ztypes_linux.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1773 Revert "Change subnets for traefik_alb_anon only when enabling NAT gateway"
  compute/k8s-services/main.tf
Labels: release:minor

#1775 chore(deps): update dependency ami_id to ami-04c07ee7e34c94256
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1776 chore(deps): update golang docker tag to v1.24.2
  azure-pipelines.yaml
Labels: release:patch

#1778 chore(deps): update terraform azuread to v3.3.0
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/security/azure-app-delegated-permissions-grant/versions.tf
  _sub/security/azure-app-delegated-permissions-grant/versions.tofu
  _sub/security/azure-app-registration/versions.tf
  _sub/security/azure-app-registration/versions.tofu
  _sub/security/azure-app-role-assignment/versions.tf
  _sub/security/azure-app-role-assignment/versions.tofu
  _sub/security/azuread-group/versions.tf
  _sub/security/azuread-group/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1780 Add support for IRSA for the Flux CD source controller
  _sub/compute/k8s-fluxcd/main.tf
  _sub/compute/k8s-fluxcd/values/flux-system-patch.yaml
  _sub/compute/k8s-fluxcd/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1782 Added new IAM role for Capability accounts; to be used for managing selfservice ssm
  _sub/security/iam-policies/main.tf
  _sub/security/iam-policies/outputs.tf
  security/org-account-context/dependencies.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: good first issue, release:minor

#1781 Upgrade Flux CD in QA
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1784 Add module for setting up IAM trust between Flux CD source controller and AWS account with ECR
  security/iam-ecr-access/main.tf
  security/iam-ecr-access/providers.tf
  security/iam-ecr-access/vars.tf
  security/iam-ecr-access/versions.tf
  security/iam-ecr-access/versions.tofu
Labels: release:minor

#1785 Make sure hardened accounts can be created from scratch by adding necessary dependencies
  _sub/security/hardened-account/main.tf
  security/org-account-assume/main.tf
Labels: release:major

#1786 Disable default standards for security hub, and make it into a optional variable instead
  _sub/security/hardened-account/main.tf
  _sub/security/hardened-account/vars.tf
  security/org-account-assume/main.tf
  security/org-account-assume/vars.tf
Labels: release:patch

#1787 fix(deps): update module github.com/aws/aws-lambda-go to v1.48.0
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:patch

#1790 chore(deps): update dependency ami_id to ami-02d2dc7182561a3cb
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1793 feat: add qa nat gateways
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1788 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.24 [security]
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1794 Add IAM action to watch recreation of SSO account assigments
  _sub/security/iam-policies/main.tf
Labels: release:minor
