Repository dfds/infrastructure-modules, pull requests merged in 2025-01, with the labels that each got.

#1669 chore(deps): update dependency ami_id to ami-0cb589ef6879c6760
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:patch

#1671 chore(deps): update dependency ami_id to ami-0b66c941d91ad0d01
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1672 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.18
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1673 fix(deps): update module sigs.k8s.io/controller-runtime to v0.19.4
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1674 Add feature toggle for enabling/disabling Grafana in kube-prometheus-stack
  _sub/compute/helm-kube-prometheus-stack/main.tf
  _sub/compute/helm-kube-prometheus-stack/outputs.tf
  _sub/compute/helm-kube-prometheus-stack/values/grafana.yaml
  _sub/compute/helm-kube-prometheus-stack/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/outputs.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1675 Feat/add 1password connect server module
  _sub/security/helm-1password-connect/dependencies.tf
  _sub/security/helm-1password-connect/iam.tf
  _sub/security/helm-1password-connect/main.tf
  _sub/security/helm-1password-connect/vars.tf
  _sub/security/helm-1password-connect/versions.tf
  _sub/security/helm-1password-connect/versions.tofu
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: release:minor

#1676 Add label norelease to changes in the test/integration directory
  renovate.json
Labels: norelease

#1680 Verify that vendoring is actually taking place before compiling and commiting
  .github/workflows/vendor-go.yml
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1685 Removing monitoring-grafana.monitoring/api/health from Blacbox explorer.
  compute/k8s-services/dependencies.tf
Labels: norelease

#1686 chore(deps): update terraform kubectl to ~> 1.19.0
  _sub/compute/helm-kyverno/versions.tf
  _sub/compute/helm-kyverno/versions.tofu
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1687 Add support for overriding EKS addon version for EFS. Plus formatting
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
Labels: release:minor

#1689 Fix problem with exit code on diff
  .github/workflows/vendor-go.yml
Labels: norelease

#1688 fix(deps): update kubernetes packages to v0.32.1
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/k8s.io/api/resource/v1alpha3/generated.proto
  test/integration/suite/vendor/k8s.io/api/resource/v1alpha3/types.go
  test/integration/suite/vendor/k8s.io/api/resource/v1alpha3/types_swagger_doc_generated.go
  test/integration/suite/vendor/k8s.io/api/resource/v1beta1/generated.proto
  test/integration/suite/vendor/k8s.io/api/resource/v1beta1/types.go
  test/integration/suite/vendor/k8s.io/api/resource/v1beta1/types_swagger_doc_generated.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1692 fix(deps): update module sigs.k8s.io/controller-runtime to v0.20.0
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/marshal.go
  test/integration/suite/vendor/modules.txt
  test/integration/suite/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/restmapper.go
  test/integration/suite/vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  test/integration/suite/vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
Labels: bug, norelease

#1693 chore(deps): update terraform github to ~> 6.5.0
  _sub/compute/atlantis/versions.tf
  _sub/compute/atlantis/versions.tofu
  _sub/compute/druid-operator/versions.tf
  _sub/compute/druid-operator/versions.tofu
  _sub/compute/github-arc-runners/versions.tf
  _sub/compute/github-arc-runners/versions.tofu
  _sub/compute/github-arc-ss-controller/versions.tf
  _sub/compute/github-arc-ss-controller/versions.tofu
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tofu
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-fluxcd/versions.tofu
  _sub/compute/k8s-traefik-flux/versions.tf
  _sub/compute/k8s-traefik-flux/versions.tofu
  _sub/compute/nvidia-device-plugin/versions.tf
  _sub/compute/nvidia-device-plugin/versions.tofu
  _sub/compute/trivy-operator/versions.tf
  _sub/compute/trivy-operator/versions.tofu
  _sub/examples/podinfo/versions.tf
  _sub/examples/podinfo/versions.tofu
  _sub/monitoring/blackbox-exporter/versions.tf
  _sub/monitoring/blackbox-exporter/versions.tofu
  _sub/monitoring/goldpinger/versions.tf
  _sub/monitoring/goldpinger/versions.tofu
  _sub/monitoring/grafana/versions.tf
  _sub/monitoring/grafana/versions.tofu
  _sub/monitoring/helm-exporter/versions.tf
  _sub/monitoring/helm-exporter/versions.tofu
  _sub/monitoring/kafka-exporter/versions.tf
  _sub/monitoring/kafka-exporter/versions.tofu
  _sub/monitoring/metrics-server/versions.tf
  _sub/monitoring/metrics-server/versions.tofu
  _sub/security/atlantis-github-configuration/versions.tf
  _sub/security/atlantis-github-configuration/versions.tofu
  _sub/security/external-secrets/versions.tf
  _sub/security/external-secrets/versions.tofu
  _sub/security/falco/versions.tf
  _sub/security/falco/versions.tofu
  _sub/security/helm-1password-connect/versions.tf
  _sub/security/helm-1password-connect/versions.tofu
  _sub/storage/external-snapshotter/versions.tf
  _sub/storage/external-snapshotter/versions.tofu
  _sub/storage/velero/versions.tf
  _sub/storage/velero/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1694 chore(deps): update dependency ami_id to ami-0a257e3c805be0ce8
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1695 chore(deps): update golang docker tag to v1.23.5
  azure-pipelines.yaml
Labels: release:patch

#1700 Update pre-commit check. Replace tflint and add checkov
  .pre-commit-config.yaml
Labels: norelease

#1701 fix(deps): update module sigs.k8s.io/controller-runtime to v0.20.1
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1702 Use latest pipeline image and Atlantis image
  azure-pipelines.yaml
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1703 chore(deps): update dependency ami_id to ami-0450bfd9dee9bca43
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1704 Rename the root terraform.hcl to root.hcl and update references to it
  test/integration/_global/eks-public-s3-bucket/terragrunt.hcl
  test/integration/_global/s3-bucket-velero/terragrunt.hcl
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
  test/integration/root.hcl
Labels: norelease

#1705 fix(deps): update module github.com/traefik/traefik/v2 to v2.11.19
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease
