Repository dfds/infrastructure-modules, pull requests merged in 2025-05, with the labels that each got.

#1799 chore(deps): update terraform tls to ~> 4.1.0
  _sub/compute/k8s-fluxcd/versions.tf
  _sub/compute/k8s-fluxcd/versions.tofu
  _sub/security/iam-oidc-provider/versions.tf
  _sub/security/iam-oidc-provider/versions.tofu
  compute/eks-ec2/versions.tf
  compute/eks-ec2/versions.tofu
  security/iam-ecr-access/versions.tf
  security/iam-ecr-access/versions.tofu
  security/ssh-keypair/versions.tf
  security/ssh-keypair/versions.tofu
  storage/s3-velero-backup/versions.tf
  storage/s3-velero-backup/versions.tofu
Labels: release:patch

#1797 chore(deps): update dependency ami_id to ami-0c3d2565c154d4253
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1804 fix(deps): update module github.com/traefik/traefik/v3 to v3.4.0
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1806 Add support for accessMode: ReadOnly in Velero in order to support restore from replicated bucket
  _sub/storage/velero/main.tf
  _sub/storage/velero/values/patch.yaml
  _sub/storage/velero/vars.tf
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1807 Allow OrgRole to use s3:PutBucketPublicAccessBlock to deny public bucket ACL
  security/org-policies/preventive.tf
Labels: release:patch

#1808 Support bucket encryption for bucket replication
  _sub/storage/s3-bucket-lifecycle/main.tf
  _sub/storage/s3-bucket-lifecycle/vars.tf
  compute/k8s-services/vars.tf
  storage/s3-velero-backup/vars.tf
Labels: release:minor

#1809 Allow for overriding the identifier urls set in the AZ app registration used for alb
  compute/k8s-services/main.tf
  compute/k8s-services/vars.tf
Labels: release:minor

#1810 Upgrade pipeline images and commands
  .trunk/trunk.yaml
  azure-pipelines.yaml
  src/qa-test-eks.sh
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1813 chore(deps): update golang docker tag to v1.24.3
  azure-pipelines.yaml
Labels: norelease

#1811 chore(deps): update dependency ami_id to ami-0295b7d66a86049ce
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1812 chore(deps): update dependency go to v1.24.3
  test/integration/suite/go.mod
Labels: norelease

#1814 Upgrade helm charts for Traefik, Velero and Atlantis
  .trunk/trunk.yaml
  test/integration/eu-west-1/k8s-qa/services/terragrunt.hcl
Labels: norelease

#1815 Migrate deprecated managed_policy_arns to using aws_iam_role_policy_attachment
  _sub/network/vpc-peering-requester/main.tf
  security/legacy-account-context/main.tf
  security/org-account-context/main.tf
Labels: release:minor

#1816 Use only one sub module for setting alternate security contact details
  _sub/security/hardened-account/main.tf
  _sub/security/hardened-account/vars.tf
  security/legacy-account-context/main.tf
  security/legacy-account-context/vars.tf
  security/org-account-assume/main.tf
  security/org-account-assume/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:major

#1821 fix(deps): update module github.com/fluxcd/pkg/apis/meta to v1.12.0
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/github.com/fluxcd/pkg/apis/meta/conditions.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1818 fix(deps): update kubernetes packages to v0.33.1
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/k8s.io/apimachinery/pkg/util/yaml/decoder.go
  test/integration/suite/vendor/modules.txt
Labels: norelease

#1817 chore(deps): update dependency ami_id to ami-0cef644e0ab76a166
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1820 chore(deps): update terraform azuread to v3.4.0
  _sub/compute/helm-kube-prometheus-stack/versions.tf
  _sub/compute/helm-kube-prometheus-stack/versions.tofu
  _sub/security/azure-app-delegated-permissions-grant/versions.tf
  _sub/security/azure-app-delegated-permissions-grant/versions.tofu
  _sub/security/azure-app-registration/versions.tf
  _sub/security/azure-app-registration/versions.tofu
  _sub/security/azure-app-role-assignment/versions.tf
  _sub/security/azure-app-role-assignment/versions.tofu
  _sub/security/azuread-group/versions.tf
  _sub/security/azuread-group/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch

#1822 Update apiVersion for External Secrets Operator
  _sub/compute/atlantis/values/kubeconfigs.yaml
  _sub/security/helm-1password-connect/dependencies.tf
Labels: release:major

#1824 Add modules for handling customer managed keys in KMS that can be used by multiple principals
  _sub/security/kms-key/main.tf
  _sub/security/kms-key/outputs.tf
  _sub/security/kms-key/vars.tf
  _sub/security/kms-key/versions.tf
  _sub/security/kms-key/versions.tofu
  security/shared-symmetric-key/main.tf
  security/shared-symmetric-key/outputs.tf
  security/shared-symmetric-key/providers.tf
  security/shared-symmetric-key/vars.tf
  security/shared-symmetric-key/versions.tf
  security/shared-symmetric-key/versions.tofu
Labels: release:minor

#1826 Add multi-region support for shared KMS key
  _sub/security/kms-key/main.tf
  _sub/security/kms-key/outputs.tf
  _sub/security/kms-key/vars.tf
  security/shared-symmetric-key/main.tf
  security/shared-symmetric-key/outputs.tf
  security/shared-symmetric-key/providers.tf
  security/shared-symmetric-key/vars.tf
Labels: release:minor

#1827 Add missing policy to KMS replica keys
  _sub/security/kms-key/main.tf
Labels: release:patch

#1828 Add support for (optionally) specifying a KMS key as default encryption key for EBS volumns in hardened accounts.
  _sub/security/hardened-account/main.tf
  _sub/security/hardened-account/vars.tf
  security/legacy-account-context/main.tf
  security/legacy-account-context/vars.tf
  security/org-account-assume/main.tf
  security/org-account-assume/vars.tf
  security/org-account-context/main.tf
  security/org-account-context/vars.tf
Labels: release:minor

#1829 enabling adding kms for ebs encryption in eks
  _sub/compute/eks-addons/main.tf
  _sub/compute/eks-addons/vars.tf
  azure-pipelines.yaml
  compute/eks-ec2/main.tf
  compute/eks-ec2/vars.tf
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: release:minor

#1835 fix(deps): update module github.com/traefik/traefik/v2 to v3
  test/integration/suite/go.mod
  test/integration/suite/go.sum
  test/integration/suite/vendor/modules.txt
Labels: norelease
