Repository dfds/infrastructure-modules, pull requests merged in 2025-07, with the labels that each got.

#1880 fix(deps): update module github.com/slack-go/slack to v0.17.3
  _sub/monitoring/alarm-notifier/lambda/go.mod
  _sub/monitoring/alarm-notifier/lambda/go.sum
Labels: release:patch

#1884 fix: use ami al2023 filter
  _sub/compute/eks-nodegroup-managed/dependencies.tf
Labels: release:patch

#1886 feat: upgrade qa control plane to 1.33
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1885 Allow IPAM pool sharing with OUs instead of per account basis
  _sub/security/org-account-query/main.tf
  _sub/security/org-account-query/outputs.tf
  network/ipam/main.tf
  network/ipam/vars.tf
Labels: release:minor

#1887 feat: upgrade qa eks nodes to 1.33
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1889 chore(deps): update dependency go to v1.24.5
  test/integration/suite/go.mod
Labels: norelease

#1894 feat: adds eks addon version and renovate config to qa
  renovate.json
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1896 fix: pin ebs csi driver in qa and manage with renovate
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1888 chore(deps): update dependency ami_id to ami-01e91e4b5486e215c
  test/integration/eu-west-1/k8s-qa/cluster/terragrunt.hcl
Labels: norelease

#1899 chore(deps): update terraform kubernetes to ~> 2.38.0
  _sub/compute/eks-addons/versions.tf
  _sub/compute/eks-addons/versions.tofu
  _sub/compute/k8s-blaster-namespace/versions.tf
  _sub/compute/k8s-blaster-namespace/versions.tofu
  _sub/compute/k8s-clusterrole/versions.tf
  _sub/compute/k8s-clusterrole/versions.tofu
  _sub/compute/k8s-namespace/versions.tf
  _sub/compute/k8s-namespace/versions.tofu
  _sub/compute/k8s-priority-class/versions.tf
  _sub/compute/k8s-priority-class/versions.tofu
  _sub/compute/k8s-service-account/versions.tf
  _sub/compute/k8s-service-account/versions.tofu
  _sub/compute/k8s-subnet-exporter/versions.tf
  _sub/compute/k8s-subnet-exporter/versions.tofu
  _sub/monitoring/aws-node/versions.tf
  _sub/monitoring/aws-node/versions.tofu
  compute/eks-ec2/versions.tf
  compute/eks-ec2/versions.tofu
  compute/k8s-services/versions.tf
  compute/k8s-services/versions.tofu
Labels: release:patch
